# Data

This chapter is only really relevant to LIFE363 students. As part of your honours project, you will be collecting and analysing comparative data. In order to do this appropriately, you need to understand the nature of the data available and how it should be interpreted.

## Comparative data

The basic format of comparative data is so-called "wide" data. Wide data has a column for each variable and each row is an observation. For a species-level comparative dataset, each row would be a species. An example of this format can be seen here. Keep in mind that not all data looks like this and you may have to reshape it to fit the format best suited for your analysis.

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=TRUE}
require(geiger)
data("geospiza")
x <- round(geospiza$geospiza.data, 3)
knitr::kable(head(x, 7))
rm(geospiza, x)
```

An ideal comparative study would have data for every single species in the study lineage. So if we wanted to study birds, that would involve collecting data on our chosen variables for approximately 10,000 species! To go and collect such a volume of data would be a huge undertaking and far beyond the scope of an undergraduate project. 

Fortunately, there is a huge amount of data available in the literature already and so nobody expects you to go out and measure the wingspan of every single bird species. In fact, there are many lifetimes worth of data collection that are very easily accessible online.

## Databases

A large amount of data is stored in data repositories. The most well known of these is probably [Dryad][Dryad] where researchers deposit the data used in their own work. The purpose of doing this is so that others can access the data to check the work as well as use the data in further research. You will often find links to Dryad in the methods sections and supplementary information of scientific papers. In fact, some journals make it a condition of publication that authors make their data available for scrutiny and further use. 

In addition to data from individual studies, there are a few projects that have sought to gather large amounts of data. For example, a group of researchers gathered data on 25 ecological and life history variables covering as many sepceies of mammal as possible [@Jones09]. The project took a lot of effort and the resulting database (called PanTHEIRA) is available [here][pantheria] as part of the [Ecological Data Wiki][EDW] site.

There are many more places that data can be sourced from that are too numerous to be listed here.

## Data Riches

The volume of data about the natural world that is available to us is truly a great thing. It gives us as scientists the scope to ask big questions. However, we cannot be carelessly gathering up every scrap of information we come across and blindly lumping it all together. Collecting data from multiple sources like this requires us to be critical at every stage. A paper by Borries *et al.* [-@Borries16] sums up the issue quite well.

When gathering a large amount of data on as many species as possible, mistakes are inevitable. This is a simple fact of life. Typos, copying errors and corrupted files are all potential sources of error. Usually, they are easy to spot but for comparative researchers, it is unreasonable to assume that we will be experts in every species we are studying. So it may be difficult for us to spot if two species' data got switched or the decimal point is in the wrong place.

On a similar note, if we gather data from multiple sources, we need to understand the metos used to gather those data. If different methodologies were used in different sources, it may be the case that the data are not directly comparable. We would also need to be careful lumping together data from sources with different sample sizes. If one study reports a body mass for a species based on measurements of two individuals and another reports the mass based on 42 species, the second is likely to be a better estimate of species average. Be aware however, that this may not be true if the larger sample included juveniles or captive animals. Or perhaps the species exhibits sexual dimorphism and this wasn't accounted for in the larger sample. We need to be aware of all of this!

Borries *et al.* [-@Borries16] put together 4 guiding principles that I think it is useful to follow.

1. Include explicit **definitions** for every variable collected.
2. Include **metadata** with each datum collected.
3. **Document** the procedures used to collect and validate the data.
4. All data collected should be **universally accessible**.

During your project, use these principles when gathering and preparing data and you'll be able to prevent a whole lot of misery and stress!

[Dryad]: https://datadryad.org/stash/ "Dryad"
[pantheria]: https://ecologicaldata.org/wiki/pantheria "pantheria"
[EDW]: https://ecologicaldata.org/home "EDW"
