% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Comparative Methods Workshops},
  pdfauthor={Chris Mitchell},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\usepackage{amsthm}
\usepackage{float}
\makeatletter
\def\thm@space@setup{%
  \thm@preskip=8pt plus 2pt minus 4pt
  \thm@postskip=\thm@preskip
}
\makeatother
\usepackage[]{natbib}
\bibliographystyle{plainnat}

\title{Comparative Methods Workshops}
\author{Chris Mitchell}
\date{}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{welcome}{%
\chapter{Welcome}\label{welcome}}

Welcome to the online support materials for the Comparative Research Group at the University of Liverpool. The CRG is made up of staff and students engaging in comparative research across various areas of evolutionary biology.

\hypertarget{for-students}{%
\section{For students}\label{for-students}}

The materials here are intended to support you through your LIFE363 honours project. For this project you will be performing a comparative study (see \textbf{chapter 1} for more information) on an area of your choosing. At first, this is a daunting task but developing your own research here is excellent experience and gives you the opportunity to research an area that really interests you.

The vast majority of statistics here are performed in R \citep{R}. You were introduced to R in LIFE223 as a powerful and flexible tool for statistical analysis. \textbf{Chapter 2} contains a brief refresher on some of the basics of R in case you need it. For more detailed recaps, please revisit your materials from LIFE223 as some of the code you wrote is likely to be useful this year!

Throughout this book you will see examples of R code and output like this.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{print}\NormalTok{(answer)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Forty-two"
\end{verbatim}

The code can be copied and pasted into your own version of R as you see fit. However, I would recommend that for the first time you are using a piece of code, type it out for yourself. This will help you get to grips with what each argument means.

You will also see some interactive R windows where you can enter your code directly into this book and an online version of R will run it. This should give you an opportunity to learn more complex things and develop your R skills dramatically.

The rest of the book is populated with workshops and materials to help you learn specific comparative statistical methods. Some of these will be extensions of what you already met in LIFE223. \textbf{Chapter 6} looks at phylogenetically controlled ANOVA and \textbf{chapter 14} is all about phylogenetic regression.

Other methods may be entirely new to you such as ancestral state reconstruction (\textbf{chapters 7 - 10}) or path analysis (\textbf{chapter 15}). Don't be intimidated by this. All the code you need is gathered here and will remain available as long as you need it.

\hypertarget{intro}{%
\chapter{Introduction}\label{intro}}

This chapter contains a very brief overview of the research we do in the \textbf{Comparative Research Group}. Taxonomically, the work done by group members is extremely broad. We've had projects on primates, octopuses, domestic mammals, birds and more! Here is a sample of titles from previous students.

\begin{itemize}
\tightlist
\item
  Identification of a cognitive niche in benthic octopods and possible areas for future study on cephalopod intelligence.
\item
  Evolutionary precursors for the domestication of Artiodactyla.
\item
  You are not what you eat: Lack of morphological convergence in beak and body size between the nectarivorous avian families Trochilidae and Meliphagidae.
\item
  Investigating how lifestyle factors affect lifespan in reptiles.
\item
  Ecological processes causing encephalisation in Madagascan lemurs.
\end{itemize}

\hypertarget{what-is-the-comparative-method}{%
\section{What is the comparative method?}\label{what-is-the-comparative-method}}

The comparative method is a catch-all term for a suite of approaches that involve using comparisons to answer scientific questions. In evolutionary biology, the comparative method refers to making comparisons between species or populations in order to identify patterns and relationships between traits of interest. Used correctly, this approach can be very powerful and allows us to ask large-scale questions about evolutionary patterns, adaptive processes and coevolutionary relationships.

The most basic kind of comparative study is comparing one species or lineage to another. For example, a recent paper made waves in the paleontology community by demostrating (after years of debate) that \emph{Spinosaurus aegypticus} lived an aquatic lifestyle \citep{Ibrahim20}. The analysis centered around some newly recovered tail vertebrae with extremely long (1m!) spines. The tail of \emph{Spinosaurus} was compared to other animals including terrestrial theropods like \emph{Allosaurus} and semi-aquatic tetratpods such as the crocodile. This comparison showed that the \emph{Spinosaurus} tail was indeed specialised for powerful propulsion through the water (like a crocodile), seemingly settling the debate over whether any non-avian dinosaurs invaded the water.

Other comparative studies take data gathered from many species and search for patterns within that group. Studies like this rely a great deal on work done by others. For example, Simon Reader and colleagues \citeyearpar{Reader11} carried out an extensive literature search looking for examples of five behavioural traits in many species of primate in over 4000 articles published over 75 years. The resulting database included examples of innovation, social learning, tool use, extractive foraging and tactical deception and was used to demonstrate a correlation between these behaviours and brain size, providing evidence of a general intelligence factor in primates similar to that in humans.

\hypertarget{tree-thinking}{%
\section{Tree thinking}\label{tree-thinking}}

Comparative studies can be great but there is a problem. In LIFE223 you learned about statistical assumptions. One of the most common and important assumptions of most statistical tests is that data are independent. To run a good comparative study we need to know that the data points we have are independent of each other. In evolutionary biology, we know that this isn't the case!

All living things exhibit a pattern of relatedness which depends on how much shared evolutionary history they have. For example, chimpanzees and human beings diverged about 6-7 million years ago. This means that they have much more shared evolutionary history than chimpanzees and \emph{Spinosaurus} which are separated by hundreds of millions of years.

The best way of visualising this pattern of relatedness is with a phylogenetic tree.

\begin{figure}[H]

{\centering \includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-4-1} 

}

\caption{A cladogram of 42 cetacean species.}\label{fig:unnamed-chunk-4}
\end{figure}

The extant species are displayed on the \textbf{tips} of the tree and are connected to each other according to the degree of relatedness by the \textbf{branches}. Figure 2.1 shows us the pattern of relatedness of 42 cetacean species. If we wanted to use these species in a comparative study to investigate the evolutionary history of the group, we would not have independent data points. This means that the assumptions of most statistical tests would be violated and we couldn't trust the results!

This is where phylogenetics comes to the rescue. We can use the pattern of relatedness described by the phylogeny to control for the non-indepedence of data points. To show you what I mean, let's consider body size in those 42 species of cetacean. If we were to show the distribution of body size in the group, we would see that the vast majority of the largest sizes are found in the mysticetes whereas the smaller species tend to be odontocetes. If we viewed these data points as all independent we might say that very large bodies have evolved 7 times in the group (once for each mysticete and once for the sperm whale) whilst small body size has evolved in all the other species (35 times).

In fact, the close relatedness of 6 of the large bodied species suggests that large body size evolved once and not independently for each of these species. Their shared evolutionary history explains why their traits (body size in this case) are so similar. The seventh example of a large body (sperm whales) does not share very much history with the other 6 and this may be of some interest to us. It suggests an independent evolution of large body size and potentially something of interest to us as researchers.

So hopefully you can see how taking phylogeny into account can be illuminating. For a broader (and much more useful) introduction to phylogenetics and its use in evolutionary biology, check out these sources:

\begin{itemize}
\tightlist
\item
  Tree Thinking: An Introduction to Phylogenetic Biology \citep{baum12}
\item
  The Comparative Approach in Evolutionary Anthropology and Biology \citep{Nunn11}
\end{itemize}

\hypertarget{recap}{%
\chapter{R recap}\label{recap}}

In LIFE223, we taught you how to use R for statistical analysis and visualising data. This chapter will contain a basic overview of some of the things from 223 that you may find useful as we proceed. You only need to bother with this if you are new to R or have blocked it from your memory since you last used it.

\hypertarget{basics}{%
\section{Basics}\label{basics}}

R works well as a calculator.

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{6}\OperatorTok{*}\DecValTok{7}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 42
\end{verbatim}

However, R is capable of a great deal more than just simple mathematical operations like multiply and divide. It also has functions that can calculate some common descriptive stats like mean and standard deviation.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 41.98682
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sd}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 4.164916
\end{verbatim}

\hypertarget{plotting}{%
\subsection{Plotting}\label{plotting}}

R is also a very flexible graphical tool. From LIFE223, you probably remember a few basic plotting functions. Each function in R has arguments that can be added to label axes or change point size as you can see in these plots.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot}\NormalTok{(x, }\DataTypeTok{ylab =} \StringTok{"Potential answers"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-9-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(x, }\DataTypeTok{xlab =} \StringTok{"Potential answers"}\NormalTok{, }\DataTypeTok{breaks =} \DecValTok{25}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-9-2} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(x, y, }\DataTypeTok{xlab =} \StringTok{"Potential answers"}\NormalTok{, }\DataTypeTok{pch =} \DecValTok{19}\NormalTok{, }\DataTypeTok{cex =} \FloatTok{0.1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-9-3} \end{center}

For much of this book, I will actually be doing most plotting in a package called \textbf{ggplot2}. This package has a slightly different syntax to get used to but the increased flexibility you have will be a good payoff. Plus the plots look quite nice.

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-10-1} \end{center}

\hypertarget{the-working-directory}{%
\subsection{The working directory}\label{the-working-directory}}

The working directory is the folder on your computer where R's attention is focused. This is where you should store any files you need R to open. You can find out the path of the current working directory using the function \textbf{getwd()}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{getwd}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "/Users/chrismitchell/Google Drive/University of Liverpool/GitHub Stuff/bookdownCRG"
\end{verbatim}

If this isn't the folder we want as our working directory, we can just as easily change it with \textbf{setwd()}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{setwd}\NormalTok{(}\StringTok{"\textasciitilde{}/Desktop/My R Folder"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

If you are using RStudio there is also a shortcut to do this in the \emph{Files} pane (usually bottom right). Use this pane to navigate to your chosen directory and then use the drop down menu under \emph{More} (look for a blue cog) to set the current folder as your working directory.

If you aren't using RStudio, I'd strongly suggest you start. It's much more user friendly than base R.

\hypertarget{loading-data}{%
\subsection{Loading data}\label{loading-data}}

Data comes in many forms and R is capable of reading most of them if you know the correct functions. One of the most common formats is \emph{comma separated values}. This has the file extension .csv at the end of the filename. If you open a .csv file with MS Excel or Numbers, you will see that it usually looks much like a spreadsheet. To load a .csv data file into R, use the function \textbf{read.csv()} as shown here.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data \textless{}{-}}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\DataTypeTok{file =} \StringTok{"DATAFILE.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

For other data formats, you may require a different function. For example, data may be provided as a text file (extension .txt). In this case, you need \textbf{read.table()}. Note that with this function you need to specify that your data has a header (a top row with names for columns) whereas \textbf{read.csv()} assumes this by default.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data \textless{}{-}}\StringTok{ }\KeywordTok{read.table}\NormalTok{(}\DataTypeTok{file =} \StringTok{"DATAFILE.txt"}\NormalTok{, }\DataTypeTok{header =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{subsetting}{%
\subsection{Subsetting}\label{subsetting}}

Let's say I want to subset my data based on a certain condition. I can achieve this multiple ways but one of the simplest is the function subset.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{newdata \textless{}{-}}\StringTok{ }\KeywordTok{subset}\NormalTok{(data, species }\OperatorTok{==}\StringTok{ "Homo sapiens"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

This function takes a subset of the object \emph{data} and applies the rule that the value of each row in the column \emph{species} be \emph{Homo sapiens}. Thus it extracts the lines of data that are from human beings.

\hypertarget{errors}{%
\section{Errors}\label{errors}}

Error messages are a part of life with R. You are not expected to be able to interpret every single one immediately and you definitely shouldn't panic or give up when you get one.

Here's a basic error message:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data \textless{}{-}}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"mydaat.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Warning in file(file, "rt"): cannot open file 'mydaat.csv': No such file or
directory
\end{verbatim}

\begin{verbatim}
Error in file(file, "rt"): cannot open the connection
\end{verbatim}

The message tells me that R ``cannot open the connection'' and no such file exists. This means that R cannot find the file I was looking for in the current working directory. It could be because I haven't set the correct working directory or the file is there but in a different format. In this case, the error has appeared because I have spelled the name incorrectly. I have sent R looking for a file called \emph{mydaat.csv} instead of \emph{mydata.csv}. Always remember that R is a useful idiot and will only do exactly what you tell it to do!

\hypertarget{google}{%
\section{Google}\label{google}}

The most important skill you need for using R is the ability to use Google (other search engines are available). It may seem odd but almost any problem you will ever encounter with R can be solved by a quick Google search.

If you come up against a confusing error message, copy and paste the message into Google. You will quickly land on one of the forums where someone else has asked about the same error message. The odds are pretty good you'll discover an explanation for the problem there.

If you don't know how to do something, pop the name of what you want to do into Google and add ``in R'' at the end and there will almost always be a tutorial on the first page of results with exactly what you need.

Seriously, Google is your strongest ally here. The community of R users has populated the internet with endless advice and guidance for every level from beginner to the most advanced of users. That brings me to my next point\ldots{}

\hypertarget{stealing}{%
\section{Stealing}\label{stealing}}

If imitation is the greatest form of flattery then learning to code in R is just about the most flattering thing you can do. The internet is teeming with examples of R code for all kinds of purposes including in this very book. Take it without thinking twice.

You will have acheived a pretty good level of skill in R when you can take someone else's code and edit it for your own purposes. This is the \textbf{core skill} of R and once you can do that, you'll be unstoppable.

\hypertarget{phylogenetics}{%
\chapter{Phylogenetic trees and where to find them}\label{phylogenetics}}

This chapter is a brief overview of some key concepts that may be useful when performing comparative research.

\hypertarget{phylogeny}{%
\section{Phylogeny}\label{phylogeny}}

Phylogeny is the term used to describe the evolutionary history of a group of species. The most common representation of phylogeny is a phylogenetic tree. There is a lot of terminology around phylogenetic trees. Here we will start with the very basics that will come up a lot in this book.

The \textbf{tips} of the tree represent the species/populations/individuals described by the tree. The \textbf{branches} of the tree represent the pattern of relationships between species. The \textbf{nodes} of a tree represent the most recent common ancestor of the lineages that diverge from that node. A \textbf{clade} is a monophyletic grouping of lineages. A grouping is \textbf{monophyletic} only if all members of that group descend from a common ancestor to the exclusion of others. for example, humans and apes form a monophyletic grouping but humans, apes and parrots do not.

Here is an example of a phylogenetic tree displaying the relationships of modern dog breeds taken from a nice paper investigating the evolutionary history of the domestic dog \citep{Parker17}

The tree shown above is a \textbf{cladogram} meaning that the lengths of the branches do not carry any real meaning. This tree is only useful for interpreting the relatedness of the species. It does not give us any information about the amount of evolutionary change or the amount time between nodes.

By contrast, the following tree has \textbf{branch lengths}. The tree is based on genetic analysis of 173 species of hymenoptera (bees, ants and wasps) \citep{Peters17}. In this tree, the branch lengths represent time (in millions of years) as calculated from analysis of over 3,000 genes and calibrated using fossils.

Branch lengths do not always represent evolutionary distance as time. In some cases, evolutionary distance is represented as the amount of change on each branch. The next tree was built based on a brain development gene (MCPH1) in cetaceans (whales, dolphins and porpoises) \citep{McGowen11}. On a tree like this, longer branches indicate more character changes along the branch. In this case the character changes will be changes in genetic sequence but for other trees it may be morphological characters, protein sequences characters or a combination.

\hypertarget{building-trees}{%
\section{Building trees}\label{building-trees}}

Developments in the field of phylogenetics have meant that there are many ways to construct a phylogeny. Many of the modern methods are highly sophistaicated and for now, these are not the subject of this book. However, it may help you to have a brief introduction to the logic behind building a phylogeny.

\hypertarget{locating-trees}{%
\section{Locating trees}\label{locating-trees}}

\hypertarget{file-format}{%
\subsection{File format}\label{file-format}}

\hypertarget{w1plotting}{%
\chapter{Plotting trees in R}\label{w1plotting}}

\hypertarget{phylogenies-in-r}{%
\section{Phylogenies in R}\label{phylogenies-in-r}}

From LIFE223, you know R as a powerful statistical tool. You will also be aware that it is an incredibly flexible tool for plotting data. In this workshop, we will be working with phylogenies in R and manipulating them to produce informative plots.

\hypertarget{packages-used}{%
\subsection{Packages used}\label{packages-used}}

In this section we'll mostly be using a package called ggtree \citep{Yu17, Yu18}. To install it, we need another package called \textbf{BiocManager} \citep{Morgan19}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{install.packages}\NormalTok{(}\StringTok{"BiocManager"}\NormalTok{)}
\NormalTok{BiocManager}\OperatorTok{::}\KeywordTok{install}\NormalTok{(}\StringTok{"ggtree"}\NormalTok{)}
\KeywordTok{library}\NormalTok{(ggtree)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggtree)}
\end{Highlighting}
\end{Shaded}

We will also need to use phylobase \citep{phylobase}, ggimage \citep{Yu19} and it would help to have the tidyverse packages loaded \citep{Wickham17} since we'll be using the syntax of ggplot2. If you get an error message, make sure the packages are installed first.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyverse)}
\KeywordTok{library}\NormalTok{(phylobase)}
\KeywordTok{library}\NormalTok{(ggimage)}
\end{Highlighting}
\end{Shaded}

\hypertarget{importing-your-tree}{%
\section{Importing your tree}\label{importing-your-tree}}

Let's start by importing a tree. Make sure your working directory is set to wherever you have saved the tree\_newick file. If you run this line, you should see an object called ``tree'' appear in your global environment.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tree \textless{}{-}}\StringTok{ }\KeywordTok{read.tree}\NormalTok{(}\StringTok{"tree\_newick.nwk"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

If we take a look at the structure of our tree object using the \textbf{str} function we can see that the tree is stored as an object of class \textbf{phylo}. If you are using a block of trees (more on this subsequent chapters) it will be an object of class \textbf{multiphylo}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(tree)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
List of 4
 $ edge       : int [1:24, 1:2] 14 15 16 17 18 19 20 20 19 18 ...
 $ edge.length: num [1:24] 4 13 10 3 8 6 4 4 5 6 ...
 $ Nnode      : int 12
 $ tip.label  : chr [1:13] "A" "B" "C" "D" ...
 - attr(*, "class")= chr "phylo"
 - attr(*, "order")= chr "cladewise"
\end{verbatim}

We can see a list of 4 elements of the tree object. The first (\textbf{edge}) contains the edges (also known as branches) of the phylogeny and their labels. The next is \textbf{edge.length} which contains the lengths of the branches if present (see \textbf{chapter 3} for more details). \textbf{Nnode} specifies the number of nodes and finally \textbf{tip.label} contains the labels of the tips. In this case, we just have letters for tip labels.

Things are often clearer when we plot them. We can do this for trees with the \textbf{plot} function in base R. This function is incredibly versatile and you should recognise it from LIFE223. Here we are using very different arguments.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(tree)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-28-1} \end{center}

This plot is fine for a quick check to make sure the tree looks as we expected it to. Let's look at making a more attractive plot with ggtree.

\hypertarget{ggtree}{%
\section{ggtree}\label{ggtree}}

The package ggtree is an extension of \textbf{ggplot2}, a popular plotting package from the \textbf{tidyverse} family of packages. The syntax we'll be using here is a little different that what you may be used to so don't get intimidated. \textbf{ggtree} uses the same syntax as \textbf{ggplot2}. This works by creating layers (known as \textbf{geoms}) and plotting them over each other to build up the plot.

We'll start by using ggtree to plot our tree. Below is the base layer of the plot. There are many other options we can include to customise our tree. Try some out in this R window to see how they effect your plot.

\hypertarget{geoms}{%
\subsection{Geoms}\label{geoms}}

Geoms are new layers to plot on or alongside your tree. Now let's try plotting it whilst adding new layers. These geoms can be combined as you see fit. This gives you a lot of flexibility in how you plot your trees. For example, we can add a geom to include the tip labels for our tree.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggtree}\NormalTok{(tree) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom\_tiplab}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-29-1} \end{center}

And we can add a title

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggtree}\NormalTok{(tree) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom\_tiplab}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"A phylogeny of letters. For some reason..."}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-30-1} \end{center}

There are many geoms you can use to add more information to your plot. Here are just a few that you may want to investigate.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{geom\_tiplab}\NormalTok{() }\CommentTok{\#adds tiplables}
\KeywordTok{geom\_tippoint}\NormalTok{() }\CommentTok{\#adds points at the tips}
\KeywordTok{geom\_nodepoint}\NormalTok{() }\CommentTok{\#adds points at the nodes}
\KeywordTok{geom\_nodelab}\NormalTok{() }\CommentTok{\#adds labels for nodes}
\KeywordTok{geom\_cladelabel}\NormalTok{() }\CommentTok{\#adds labels for clades}
\end{Highlighting}
\end{Shaded}

\hypertarget{labelling-clades}{%
\subsection{Labelling clades}\label{labelling-clades}}

As an example of what you might like to do with ggtree, let's have a look at adding some labels to identify some clades on our tree. To label clades, we need to be able to identify the node of the most recent common ancestor. The function \textbf{MRCA} in the package \textbf{phylobase} \citep{phylobase} tells us that the common ancestor of C and E is node 17.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{phylobase}\OperatorTok{::}\KeywordTok{MRCA}\NormalTok{(tree, }\DataTypeTok{tip =} \KeywordTok{c}\NormalTok{(}\StringTok{"C"}\NormalTok{, }\StringTok{"E"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 17
\end{verbatim}

We can now use the \textbf{geom\_cladelabel} geom to add a simple label for the clade descended from the appropriate node. Take note of the arguments I've added to customise the geom. You may want to play around with these options yourself to see how they work.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggtree}\NormalTok{(tree) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom\_tiplab}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom\_cladelabel}\NormalTok{(}\DataTypeTok{node=}\DecValTok{17}\NormalTok{, }\DataTypeTok{label=}\StringTok{"A clade"}\NormalTok{, }
                  \DataTypeTok{color=}\StringTok{"red2"}\NormalTok{, }\DataTypeTok{offset=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-33-1} \end{center}

Pretty good but there are other options. This is a matter of personal preference. You may prefer to overlay a translucent rectangle over your clade of interest.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggtree}\NormalTok{(tree) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom\_tiplab}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom\_hilight}\NormalTok{(}\DataTypeTok{node=}\DecValTok{17}\NormalTok{, }\DataTypeTok{fill=}\StringTok{"gold"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-34-1} \end{center}

Use the R window below to experiment with the available geoms in ggtree. Find a combination that suits you and your tree.

\hypertarget{adding-images-to-trees}{%
\section{Adding images to trees}\label{adding-images-to-trees}}

As you probably noted in chapter 3, adding images to a plot is an excellent way to annotate your tree. The ggtree package can do this as you can see here.

\begin{figure}[H]

{\centering \includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-35-1} 

}

\caption{Plot of cephalopod families annotated using ggtree and Phylopic.}\label{fig:unnamed-chunk-35}
\end{figure}

This phylogeny is annotated in a number of useful ways. The tip labels describe cephalopod families. The superorders (octopodiformes and decapodiformes) are highlighted by gold and red rectangles as well as a bar across the tips. this demonstrates how multiple geoms can combine to make a plot easy to interpret.

The most interesting thing for our purposes are the silhouettes at the root of each superorder. The octopodiformes have an octopus and the decapodiformes have a squid as example taxa from within the superorder.

\hypertarget{phylopic}{%
\subsection{Phylopic}\label{phylopic}}

The silhouettes used for that plot are from a website called \href{http://phylopic.org/}{Phylopic}. Phylopic provides open source biological silhouettes that are free to use. We're now going to look at how to get these silhouettes and use them to annotate our trees.

Let's start with loading an example tree. This one is a primate tree courtesy of \href{https://www.randigriffin.com/}{Randi Griffin}. You'll notice that I'm loading this tree using a url. This is because I'm loading a file directly from GitHub, a repository for all sorts of code and the host of this site! Randi (and many other coders) make some of the things they produce freely available through GitHub. This can be data, files or code.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{primates \textless{}{-}}\StringTok{ }\KeywordTok{read.nexus}\NormalTok{(}\StringTok{"https://raw.githubusercontent.com/rgriff23/Dissertation/master/Chapter\_2/data/tree.nex"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Let's plot the new tree first. Here I'm assigning the plot to a named object (p1) in R. This means that instead of immediately printing out the plot, R stores it in the working directory. The reason for doing this will become clear as we go on. It saves us typing out every line of code each time we want to add a new geom!

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p1 \textless{}{-}}\StringTok{ }\KeywordTok{ggtree}\NormalTok{(primates)}
\NormalTok{p1}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-38-1} \end{center}

Let's use what we already know about ggtree to customise this plot into something more useful. In particular, this plot is quite useful because it tells us the numbers of each node and we will need that later on.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggtree}\NormalTok{(primates) }\OperatorTok{+}
\StringTok{   }\KeywordTok{xlim}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{90}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{   }\KeywordTok{geom\_tiplab}\NormalTok{(}\DataTypeTok{size=}\FloatTok{1.5}\NormalTok{) }\OperatorTok{+}
\StringTok{   }\KeywordTok{geom\_label2}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{subset=}\OperatorTok{!}\NormalTok{isTip, }\DataTypeTok{label=}\NormalTok{node), }\DataTypeTok{size=}\DecValTok{2}\NormalTok{, }\DataTypeTok{color=}\StringTok{"darkred"}\NormalTok{, }\DataTypeTok{alpha=}\FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-39-1} \end{center}

Let's label the 6 primate superfamilies using the node numbers I have extracted from the previous plot. You can choose whatever colours you prefer here. I've also added some useful features to this code. the use of \textbf{xlim()} can be very useful when plotting a tree with some extra space for more details. Here I've set the limits of the x dimension (the horizontal) to be between 0 and 100. This gives me space for later annotations.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p2 \textless{}{-}}\StringTok{ }\KeywordTok{ggtree}\NormalTok{(primates) }\OperatorTok{+}
\StringTok{  }\KeywordTok{xlim}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{100}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_tiplab}\NormalTok{(}\DataTypeTok{size=}\FloatTok{1.5}\NormalTok{, }\DataTypeTok{offset=}\FloatTok{0.5}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_hilight}\NormalTok{(}\DataTypeTok{node=}\DecValTok{124}\NormalTok{, }\DataTypeTok{fill=}\StringTok{"steelblue"}\NormalTok{, }\DataTypeTok{alpha=}\FloatTok{0.5}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_hilight}\NormalTok{(}\DataTypeTok{node=}\DecValTok{113}\NormalTok{, }\DataTypeTok{fill=}\StringTok{"darkgreen"}\NormalTok{, }\DataTypeTok{alpha=}\FloatTok{0.5}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_hilight}\NormalTok{(}\DataTypeTok{node=}\DecValTok{110}\NormalTok{, }\DataTypeTok{fill=}\StringTok{"gray"}\NormalTok{, }\DataTypeTok{alpha=}\FloatTok{0.5}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_hilight}\NormalTok{(}\DataTypeTok{node=}\DecValTok{96}\NormalTok{, }\DataTypeTok{fill=}\StringTok{"pink"}\NormalTok{, }\DataTypeTok{alpha=}\FloatTok{0.5}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_hilight}\NormalTok{(}\DataTypeTok{node=}\DecValTok{89}\NormalTok{, }\DataTypeTok{fill=}\StringTok{"beige"}\NormalTok{, }\DataTypeTok{alpha=}\FloatTok{0.5}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_hilight}\NormalTok{(}\DataTypeTok{node=}\DecValTok{70}\NormalTok{, }\DataTypeTok{fill=}\StringTok{"yellow"}\NormalTok{, }\DataTypeTok{alpha=}\FloatTok{0.5}\NormalTok{) }
\NormalTok{p2}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-40-1} \end{center}

So far so good. Let's add on bars to label the superfamilies like I did for the cephalopod version. This time, I'll add the new details to the object p3 to save retyping. Take note of the arguments in each label. You may need to twist these with some trial-and-error to make sure they suit your plot window.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p3 \textless{}{-}}\StringTok{ }\NormalTok{p2 }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_cladelabel}\NormalTok{(}\DecValTok{124}\NormalTok{, }\StringTok{"Galagoidea"}\NormalTok{, }\DataTypeTok{offset=}\DecValTok{15}\NormalTok{, }\DataTypeTok{barsize=}\DecValTok{2}\NormalTok{, }\DataTypeTok{angle=}\DecValTok{90}\NormalTok{,}
                  \DataTypeTok{offset.text=}\FloatTok{1.5}\NormalTok{, }\DataTypeTok{hjust=}\FloatTok{0.5}\NormalTok{, }\DataTypeTok{fontsize=}\DecValTok{3}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom\_cladelabel}\NormalTok{(}\DecValTok{113}\NormalTok{, }\StringTok{"Lemuroidea"}\NormalTok{, }\DataTypeTok{offset=}\DecValTok{15}\NormalTok{, }\DataTypeTok{barsize=}\DecValTok{2}\NormalTok{, }\DataTypeTok{angle=}\DecValTok{90}\NormalTok{,}
                  \DataTypeTok{offset.text=}\FloatTok{1.5}\NormalTok{, }\DataTypeTok{hjust=}\FloatTok{0.5}\NormalTok{, }\DataTypeTok{fontsize=}\DecValTok{3}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_cladelabel}\NormalTok{(}\DecValTok{110}\NormalTok{, }\StringTok{"Tarsioidea"}\NormalTok{, }\DataTypeTok{offset=}\DecValTok{15}\NormalTok{, }\DataTypeTok{barsize=}\DecValTok{2}\NormalTok{, }\DataTypeTok{angle=}\DecValTok{75}\NormalTok{,}
                  \DataTypeTok{offset.text=}\FloatTok{2.5}\NormalTok{, }\DataTypeTok{hjust=}\FloatTok{0.2}\NormalTok{, }\DataTypeTok{fontsize=}\DecValTok{2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_cladelabel}\NormalTok{(}\DecValTok{96}\NormalTok{, }\StringTok{"Ceboidea"}\NormalTok{, }\DataTypeTok{offset=}\DecValTok{15}\NormalTok{, }\DataTypeTok{barsize=}\DecValTok{2}\NormalTok{, }\DataTypeTok{angle=}\DecValTok{90}\NormalTok{,}
                  \DataTypeTok{offset.text=}\FloatTok{1.5}\NormalTok{, }\DataTypeTok{hjust=}\FloatTok{0.5}\NormalTok{, }\DataTypeTok{fontsize=}\DecValTok{3}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_cladelabel}\NormalTok{(}\DecValTok{89}\NormalTok{, }\StringTok{"Hominoidea"}\NormalTok{, }\DataTypeTok{offset=}\DecValTok{15}\NormalTok{, }\DataTypeTok{barsize=}\DecValTok{2}\NormalTok{, }\DataTypeTok{angle=}\DecValTok{90}\NormalTok{,}
                  \DataTypeTok{offset.text=}\FloatTok{1.5}\NormalTok{, }\DataTypeTok{hjust=}\FloatTok{0.5}\NormalTok{, }\DataTypeTok{fontsize=}\DecValTok{3}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_cladelabel}\NormalTok{(}\DecValTok{70}\NormalTok{, }\StringTok{"Cercopithecoidea"}\NormalTok{, }\DataTypeTok{offset=}\DecValTok{15}\NormalTok{, }\DataTypeTok{barsize=}\DecValTok{2}\NormalTok{, }\DataTypeTok{angle=}\DecValTok{90}\NormalTok{,}
                  \DataTypeTok{offset.text=}\FloatTok{1.5}\NormalTok{, }\DataTypeTok{hjust=}\FloatTok{0.5}\NormalTok{, }\DataTypeTok{fontsize=}\DecValTok{3}\NormalTok{)}
\NormalTok{p3}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-41-1} \end{center}

There are some helpful details here, such as the fact that the label for Tarsioidea is off at an angle to avoid overlapping with other labels (\emph{angle = 75}). The extra arguments in these options demonstrate how much control you can exercise over each geom.

Now let's get to adding images. The way to do this is a little awkward but I think it's worth the hassle. The first thing we have to do is gather the links for each image we want to use. I've chosen to do this by building a small data frame containing the urls to the images on phylopic, the names of the super families I want to label and the nodes I want to plot the images on.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{images \textless{}{-}}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{node =} \KeywordTok{c}\NormalTok{(}\DecValTok{124}\NormalTok{,}\DecValTok{113}\NormalTok{,}\DecValTok{110}\NormalTok{,}\DecValTok{96}\NormalTok{,}\DecValTok{89}\NormalTok{,}\DecValTok{70}\NormalTok{),}
\DataTypeTok{phylopic =} \KeywordTok{c}\NormalTok{(}\StringTok{"http://phylopic.org/assets/images/submissions/}
\StringTok{7fb9bea8{-}e758{-}4986{-}afb2{-}95a2c3bf983d.512.png"}\NormalTok{,}
\StringTok{"http://phylopic.org/assets/images/submissions/}
\StringTok{bac25f49{-}97a4{-}4aec{-}beb6{-}f542158ebd23.512.png"}\NormalTok{,}
\StringTok{"http://phylopic.org/assets/images/submissions/}
\StringTok{f598fb39{-}facf{-}43ea{-}a576{-}1861304b2fe4.512.png"}\NormalTok{,}
\StringTok{"http://phylopic.org/assets/images/submissions/}
\StringTok{aceb287d{-}84cf{-}46f1{-}868c{-}4797c4ac54a8.512.png"}\NormalTok{,}
\StringTok{"http://phylopic.org/assets/images/submissions/}
\StringTok{0174801d{-}15a6{-}4668{-}bfe0{-}4c421fbe51e8.512.png"}\NormalTok{,}
\StringTok{"http://phylopic.org/assets/images/submissions/}
\StringTok{72f2f854{-}f3cd{-}4666{-}887c{-}35d5c256ab0f.512.png"}\NormalTok{),}
\DataTypeTok{species =} \KeywordTok{c}\NormalTok{(}\StringTok{"Galagoidea"}\NormalTok{,}\StringTok{"Lemuroidea"}\NormalTok{,}\StringTok{"Tarsioidea"}\NormalTok{,}
\StringTok{"Ceboidea"}\NormalTok{,}\StringTok{"Hominoidea"}\NormalTok{,}\StringTok{"Cercopithecoidea"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Once we have the urls we need in a nice dataframe, we can pipe them into the \textbf{geom\_nodelab} geom and the end product should appear.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p3 }\OperatorTok{\%\textless{}+\%}\StringTok{ }\NormalTok{images }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_nodelab}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{image =}\NormalTok{ phylopic), }\DataTypeTok{geom =} \StringTok{"image"}\NormalTok{, }\DataTypeTok{size =} \FloatTok{.04}\NormalTok{, }\DataTypeTok{nudge\_x =} \DecValTok{{-}4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-44-1} \end{center}

As you can probably tell, the images don't have to be from Phylopic. You can use any images you have the rights to in exactly the same way!

\hypertarget{further-info}{%
\section{Further info}\label{further-info}}

This chapter barely scratches the surface of what ggtree is capable of. For much more detail, have a look at Guangchuang Yu's very own Bookdown covering the topic. You can access the book by clicking \href{https://yulab-smu.github.io/treedata-book/}{here} or by running the following code in R once you have ggtree installed.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{vignette}\NormalTok{(}\StringTok{"ggtree"}\NormalTok{, }\DataTypeTok{package =} \StringTok{"ggtree"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{anova}{%
\chapter{ANOVA}\label{anova}}

Analysis of variance (ANOVA) is something you should recognise from your quantitative skills course. This chapter will begin with a brief recap before showing you how to perform phylogenetically corrected ANOVA.

\hypertarget{analysis-of-variance}{%
\section{Analysis of variance}\label{analysis-of-variance}}

Analysis of variance asks if there are differences in the mean values between 3 or more categories. If there are only two categories (Terrestrial/Aquatic for example), then you need a t-test.

In LIFE223 you analysed the results of an experiment in which corncrake hatchlings were raised on four different supplements in addition to their normal diet.

\begin{verbatim}
Warning: Ignoring unknown parameters: fun.y
\end{verbatim}

\begin{verbatim}
No summary function supplied, defaulting to `mean_se()`
\end{verbatim}

\begin{figure}[H]

{\centering \includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-48-1} 

}

\caption{Plot of weight gain in corncrake hatchlings reared on four different nutritional supplements and a control group. The mean and standard deviation of each group is plotted in blue. the mean weight gain across the entire sample is plotted in red.}\label{fig:unnamed-chunk-48}
\end{figure}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{corncrake.model \textless{}{-}}\StringTok{ }\KeywordTok{lm}\NormalTok{(WeightGain }\OperatorTok{\textasciitilde{}}\StringTok{ }\NormalTok{Supplement, }\DataTypeTok{data =}\NormalTok{ corncrake)}
\KeywordTok{anova}\NormalTok{(corncrake.model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Analysis of Variance Table

Response: WeightGain
           Df Sum Sq Mean Sq F value   Pr(>F)   
Supplement  4 357.65  89.413  5.1281 0.002331 **
Residuals  35 610.25  17.436                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

The one-way ANOVA shows that there was a significant effect of supplement on the weight gain of the corncrake hatchlings (F = 5.1, df = 4, 35, p \textless{} 0.01). The final step is to perform our multiple comparisons test.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{corncrake.aov \textless{}{-}}\StringTok{ }\KeywordTok{aov}\NormalTok{(corncrake.model)}
\KeywordTok{TukeyHSD}\NormalTok{(corncrake.aov, }\DataTypeTok{ordered =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  Tukey multiple comparisons of means
    95% family-wise confidence level
    factor levels have been ordered

Fit: aov(formula = corncrake.model)

$Supplement
                    diff       lwr       upr     p adj
None-Allvit        1.375 -4.627565  7.377565 0.9638453
Linseed-Allvit     4.250 -1.752565 10.252565 0.2707790
Sizefast-Allvit    4.750 -1.252565 10.752565 0.1771593
Earlybird-Allvit   8.625  2.622435 14.627565 0.0018764
Linseed-None       2.875 -3.127565  8.877565 0.6459410
Sizefast-None      3.375 -2.627565  9.377565 0.4971994
Earlybird-None     7.250  1.247435 13.252565 0.0113786
Sizefast-Linseed   0.500 -5.502565  6.502565 0.9992352
Earlybird-Linseed  4.375 -1.627565 10.377565 0.2447264
Earlybird-Sizefast 3.875 -2.127565  9.877565 0.3592201
\end{verbatim}

The \textbf{TukeyHSD} functions shows us the pairwise comparisons between groups. We can see (for example) that \emph{Allvit} was not significantly different from the control (difference = 1.375g, p = 0.96) but \emph{Earlybird} was significantly better than the control group (difference = 7.25g, p = 0.01).

\hypertarget{phylogenetic-correction}{%
\section{Phylogenetic correction}\label{phylogenetic-correction}}

As you know, when trying to run a similar analysis on non-independent data (such as species) we will run into problems. Garland \emph{et al} \citeyearpar{garland93} developed a simulation based approach to solve this problem. The phylogenetic ANOVA uses computer simulations of traits evolving the phylogenetic tree. The next section contains some example data and a phylogeny to demonstrate the method.

\hypertarget{example-data-analysis}{%
\section{Example data \& analysis}\label{example-data-analysis}}

The data we're using is taken from the package geiger \citep{geiger} so make sure the package is installed and loaded.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{install.packages}\NormalTok{(}\StringTok{"geiger"}\NormalTok{)}
\KeywordTok{library}\NormalTok{(geiger)}
\end{Highlighting}
\end{Shaded}

Load the data as follows. The tree and data are stored together so we'll need to save the to separate objects called \textbf{dat} and \textbf{phy}. You probably don't \emph{need} to do this but this is more similar to what you're likely to see when using your own data.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{data}\NormalTok{(}\StringTok{"geospiza"}\NormalTok{)}
\NormalTok{dat \textless{}{-}}\StringTok{ }\NormalTok{geospiza}\OperatorTok{$}\NormalTok{dat}
\NormalTok{tree \textless{}{-}}\StringTok{ }\NormalTok{geospiza}\OperatorTok{$}\NormalTok{phy}
\KeywordTok{head}\NormalTok{(dat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
                wingL  tarsusL  culmenL    beakD   gonysW
magnirostris 4.404200 3.038950 2.724667 2.823767 2.675983
conirostris  4.349867 2.984200 2.654400 2.513800 2.360167
difficilis   4.224067 2.898917 2.277183 2.011100 1.929983
scandens     4.261222 2.929033 2.621789 2.144700 2.036944
fortis       4.244008 2.894717 2.407025 2.362658 2.221867
fuliginosa   4.132957 2.806514 2.094971 1.941157 1.845379
\end{verbatim}

\begin{figure}[H]

{\centering \includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-54-1} 

}

\caption{Phylogeny of the species contained within the 'geospiza' dataset of the package geiger.}\label{fig:unnamed-chunk-54}
\end{figure}

We need to start by defining the categories for the data. It is likely that you will have already done this in your data frame. If so, just make sure the groups are stored as a factor. In this case, we'll just create some random categories to work with for the example.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{groups \textless{}{-}}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\StringTok{"A"}\NormalTok{, }\DecValTok{4}\NormalTok{), }\KeywordTok{rep}\NormalTok{(}\StringTok{"B"}\NormalTok{, }\DecValTok{5}\NormalTok{), }\KeywordTok{rep}\NormalTok{(}\StringTok{"C"}\NormalTok{, }\DecValTok{4}\NormalTok{)))}
\KeywordTok{names}\NormalTok{(groups) \textless{}{-}}\StringTok{ }\KeywordTok{rownames}\NormalTok{(dat)}
\end{Highlighting}
\end{Shaded}

An important step here (and for every phylogenetic analysis) is making sure the tree and data can be compared. To do this, we should make sure that the rownames of the data are species names and not just numbers. In this case they already are but if they aren't for you data, you can use the following code.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rownames}\NormalTok{(data) \textless{}{-}}\StringTok{ }\NormalTok{data}\OperatorTok{$}\NormalTok{SPECIES }\CommentTok{\#the column with species names in the data}
\end{Highlighting}
\end{Shaded}

The geiger package has a very useful function called \textbf{name.check} to allow us to check that the rownames of our data match the tip labels of our tree.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{name.check}\NormalTok{(tree, dat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
$tree_not_data
[1] "olivacea"

$data_not_tree
character(0)
\end{verbatim}

We can see that \emph{olivacea} is not in our data. For some analyses, mismatches like this are a problem and you will need to drop the tip from the tree. It actually doesn't matter here because the function we will be using can drop it automatically for us. However, let's see how it's done. Note the use of the function \textbf{drop.tip} from the package \textbf{ape} \citep{ape} which is an essential package to have for this kind of work!

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tree \textless{}{-}}\StringTok{ }\NormalTok{ape}\OperatorTok{::}\KeywordTok{drop.tip}\NormalTok{(tree, }\DataTypeTok{tip =} \StringTok{"olivacea"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Now we have overwritten the old tree with our pruned tree. Let's check the new one matches the data.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{name.check}\NormalTok{(tree, dat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "OK"
\end{verbatim}

All that's left now is to run the analysis. First we extract the column of interest from our data and then simply use the function \textbf{aov.phylo}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d1 \textless{}{-}}\StringTok{ }\NormalTok{dat[,}\DecValTok{1}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

You should notice some similarities and differences from the way you have run ANOVA before. We are still using a formula (the part with \(\sim\)) but not in a separate \textbf{lm} function. We need to specify the tree we want to use (\textbf{tree}) and also how many simulations we want to run. There isn't a firm rule about this but general convention is around 1000 when sampling/bootstrapping/simulations are involved.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x \textless{}{-}}\StringTok{ }\KeywordTok{aov.phylo}\NormalTok{(d1 }\OperatorTok{\textasciitilde{}}\StringTok{ }\NormalTok{groups, }\DataTypeTok{phy =}\NormalTok{ tree, }\DataTypeTok{nsim =} \DecValTok{1000}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Analysis of Variance Table

Response: dat
          Df   Sum-Sq  Mean-Sq F-value  Pr(>F) Pr(>F) given phy
group      2 0.063237 0.031619  3.0067 0.09497           0.1718
Residuals 10 0.105161 0.010516                                 
\end{verbatim}

The results table should be very familiar! The only real difference here is that you have been provided with two p-values. The first (\emph{Pr(\textgreater F)}) is the p-value without accounting for phylogeny and the second (\emph{Pr(\textgreater F) given phy}) is the value when we account for phylogeny. In both cases, there is no significant difference between groups.

As you can see, accounting for phylogeny \emph{usually} raises the p-value (makes it less significant). This shows us that not accounting for phylogeny increases the risk of type I errors (false positives).

\hypertarget{further-info-1}{%
\section{Further info}\label{further-info-1}}

For further information about the phylogenetic ANOVA, you can read the original paper by Garland \emph{et al} \citeyearpar{garland93}.

\hypertarget{asr1}{%
\chapter{Ancestral State Reconstruction I}\label{asr1}}

This chapter will take you through the code we can use to run ancestral state reconstruction with \textbf{categorical} characters. As always, remember to begin by setting your working directory to wherever you have saved the data files.

\hypertarget{data}{%
\section{Data}\label{data}}

The first thing we need to do is load some data. When you're doing this, you need to keep in mind that you should keep your workspace as well organised as possible. In practice, this means giving things good names. ``RicksDataV1.1'' is not a great name depending on how many datasets you want in there. Neither is ``data1'' if you plan on having multiple datasets (which we do). So give your data object, and all other objects, simple, useful names. My personal preference is to use the name of the group but whatever works is fine. You need to be able to keep track of everything.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{macaques \textless{}{-}}\StringTok{ }\KeywordTok{read.table}\NormalTok{(}\StringTok{"macaque\_data.txt"}\NormalTok{, }\DataTypeTok{header =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

In your environment panel there should be a data frame with 16 observations of 2 variables. This command will show us the top 6 rows of data. It's helpful to have a quick look and see R has loaded what we expected. In this case our data contains 15 species of macaque and one species of baboon alongside data regarding whether they exhibit sexual swellings or not (1/0).

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(macaques)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
              species swelling
1    Macaca_arctoides        0
2   Macaca_assamensis        0
3     Macaca_cyclopis        1
4 Macaca_fascicularis        1
5      Macaca_fuscata        1
6        Macaca_maura        1
\end{verbatim}

\hypertarget{trees}{%
\section{Trees}\label{trees}}

Now we need to load the tree using the \textbf{read.nexus} function in the package \textbf{ape} \citep{ape}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{macaque.tree \textless{}{-}}\StringTok{ }\KeywordTok{read.nexus}\NormalTok{(}\StringTok{"macaque\_tree.nex"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Let's plot the tree to make sure it loaded correctly. I've used base graphics here rather than ggtree (annotated to let you know what it does). Feel free to have a mess around with these options so you get a feel for what they do. The second function ``tiplabels'' adds some extra tip labels containing the data from the second column of our macaque data.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(macaque.tree,        }\CommentTok{\#Tree object}
     \DataTypeTok{cex =} \FloatTok{0.7}\NormalTok{,           }\CommentTok{\#Font size for tip labels}
     \DataTypeTok{label.offset =} \FloatTok{0.3}\NormalTok{,  }\CommentTok{\#Create a space between tip and label}
     \DataTypeTok{edge.color =} \StringTok{"blue"}\NormalTok{, }\CommentTok{\#Paint the branches blue}
     \DataTypeTok{edge.width =} \DecValTok{2}\NormalTok{)      }\CommentTok{\#Make the branches thicker}
\KeywordTok{tiplabels}\NormalTok{(macaques[,}\DecValTok{2}\NormalTok{], }\DataTypeTok{bg =} \StringTok{"white"}\NormalTok{, }\DataTypeTok{cex =} \FloatTok{0.7}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-68-1} \end{center}

\hypertarget{parsimony}{%
\section{Parsimony}\label{parsimony}}

Let's first generate the most parsimonious reconstruction of the history of this trait. Remember that the most parsimonious history is the one that has the fewest evolutionary transitions. Parsimony is conceptually based upon Occam's razor which states that all else being equal, the simplest explanantion is always the correct one.

The function for this is \textbf{MPR}. It takes an unrooted tree and asks you to specify the root. In our case, we'll have to unroot our tree and then re-root it by specifying that \emph{Papio anubis} is our outgroup.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mp1 \textless{}{-}}\StringTok{ }\KeywordTok{MPR}\NormalTok{(macaques[,}\DecValTok{2}\NormalTok{], }\KeywordTok{unroot}\NormalTok{(macaque.tree), }\StringTok{"Papio\_anubis"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

When we investigate mp1, we can see a list of results matched up to numbered nodes on the tree. Some nodes are clearly in state 1 and others in state 0. Interestingly some are indeterminate and could be either 0 or 1 such as nodes 19 and 20.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mp1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   lower upper
17     1     1
18     1     1
19     0     1
20     0     1
21     1     1
22     1     1
23     1     1
24     0     0
25     0     0
26     0     0
27     1     1
28     1     1
29     1     1
30     1     1
\end{verbatim}

To get an idea of what this means, we should plot it on the tree. This loop cycles through our results list and combines the lower and upper estimates for each node into a text string that we can then overlay onto that node.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mp.nodes \textless{}{-}}\StringTok{ }\KeywordTok{numeric}\NormalTok{(}\DecValTok{0}\NormalTok{)}
\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\KeywordTok{length}\NormalTok{(mp1[,}\DecValTok{1}\NormalTok{]))\{}
\NormalTok{  mp.nodes \textless{}{-}}\StringTok{ }\KeywordTok{append}\NormalTok{(mp.nodes, }\KeywordTok{paste}\NormalTok{(mp1[i,}\DecValTok{1}\NormalTok{], }\StringTok{","}\NormalTok{, mp1[i,}\DecValTok{2}\NormalTok{]))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

Once we've done that we can plot those expressions onto the tree with the function nodelabels.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(macaque.tree, }\DataTypeTok{cex =} \FloatTok{0.7}\NormalTok{, }\DataTypeTok{label.offset =} \FloatTok{0.3}\NormalTok{,}
     \DataTypeTok{edge.color =} \StringTok{"blue"}\NormalTok{, }\DataTypeTok{edge.width =} \DecValTok{2}\NormalTok{)      }
\KeywordTok{tiplabels}\NormalTok{(macaques[,}\DecValTok{2}\NormalTok{], }\DataTypeTok{bg =} \StringTok{"white"}\NormalTok{, }\DataTypeTok{cex =} \FloatTok{0.7}\NormalTok{)}
\KeywordTok{nodelabels}\NormalTok{(mp.nodes, }\KeywordTok{c}\NormalTok{(}\DecValTok{18}\OperatorTok{:}\DecValTok{31}\NormalTok{), }\DataTypeTok{bg =} \StringTok{"white"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-72-1} \end{center}

You should note that this isn't a very good plot! There are better ways to represent this information with a little code manipulation. Here's a version using \textbf{ggtree} that plots the character states as points on the tips and the reconstructed nodes.

\begin{figure}[H]

{\centering \includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-73-1} 

}

\caption{Maximum parsimony reconstruction of the evolution of conspicuous sexual swellings in macaques}\label{fig:unnamed-chunk-73}
\end{figure}

As you can see, the uncertainty in some nodes comes from the fact that there seems to be at least two equally parsimonious histories with gains and losses ocurring in different places. For any serious analysis, this is a highly unsatisfactory outcome!

\hypertarget{maximum-likelihood}{%
\section{Maximum Likelihood}\label{maximum-likelihood}}

Let's try a different approach. Maximum likelihood is different from parsimony for many reasons but most significantly, it can make use of branch length information. This is very useful in discriminating between possible histories. A longer branch means more evolutionary change (either in time or character change) and so transitions are more likely to occur on longer branches.

Let's replot the tree. Here I've changed the tiplabels function to plot the character states as colours rather than numbers. The \textbf{bg} argument is what lets me do this. In this argument I list the states (adding 1 because the first is 0) and then the function passes those states to R to assign colours based on a numbered list of standard colours.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(macaque.tree, }\DataTypeTok{cex =} \FloatTok{0.7}\NormalTok{, }\DataTypeTok{label.offset =} \FloatTok{0.4}\NormalTok{, }\DataTypeTok{edge.width =} \DecValTok{2}\NormalTok{)}
\KeywordTok{tiplabels}\NormalTok{(}\DataTypeTok{pch =} \DecValTok{21}\NormalTok{, }\DataTypeTok{bg =} \KeywordTok{as.numeric}\NormalTok{(macaques}\OperatorTok{$}\NormalTok{swelling)}\OperatorTok{+}\DecValTok{1}\NormalTok{, }\DataTypeTok{cex =} \FloatTok{1.7}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-74-1} \end{center}

To run an ancestral state reconstruction using maximum likelihood we can use the function \textbf{ace} (ancestral character estimation) in the ape package \citep{ape}. In our first reconstruction, we will make the assumption that the rate of evolution of the trait is equal across the tree by setting the model to \emph{ER} (equal rates).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m1 \textless{}{-}}\StringTok{ }\KeywordTok{ace}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ macaques}\OperatorTok{$}\NormalTok{swelling,  }\CommentTok{\#trait data}
          \DataTypeTok{phy =}\NormalTok{ macaque.tree,     }\CommentTok{\#phylogeny}
          \DataTypeTok{method =} \StringTok{"ML"}\NormalTok{,          }\CommentTok{\#method (Maximum likelihood)}
          \DataTypeTok{type =} \StringTok{"discrete"}\NormalTok{,      }\CommentTok{\#type of data (continuous or discrete)}
          \DataTypeTok{model =} \StringTok{"ER"}\NormalTok{)           }\CommentTok{\#Model of evolution}
\NormalTok{m1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
    Ancestral Character Estimation

Call: ace(x = macaques$swelling, phy = macaque.tree, type = "discrete", 
    method = "ML", model = "ER")

    Log-likelihood: -6.906593 

Rate index matrix:
  0 1
0 . 1
1 1 .

Parameter estimates:
 rate index estimate std-err
          1   0.0319  0.0191

Scaled likelihoods at the root (type '...$lik.anc' to get them for all nodes):
         0          1 
0.08625654 0.91374346 
\end{verbatim}

Looking at the results shows us the likelihood at the root (91\% in favour of state 1 here). However, it's always best to plot the results. We can represent the likelihoods at each node with a piechart. Generally speaking, piecharts are awful but when used in this way, they can actually add useful information to a plot and that's the most important point about plotting any data. In this plot, the piecharts represent the probability that each node exhibited sexual swelling (red) or concealed estrus (black). We can see that the two uncertain nodes from our parsimony analysis are now more certain. Visual inspection shows that these nodes have a greater tha 75\% probability of having exhibited sexual swellings.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(macaque.tree, }\DataTypeTok{cex =} \FloatTok{0.7}\NormalTok{, }\DataTypeTok{label.offset =} \FloatTok{0.4}\NormalTok{, }\DataTypeTok{edge.width =} \DecValTok{2}\NormalTok{)}
\KeywordTok{tiplabels}\NormalTok{(}\DataTypeTok{pch =} \DecValTok{21}\NormalTok{, }\DataTypeTok{bg =} \KeywordTok{as.numeric}\NormalTok{(macaques}\OperatorTok{$}\NormalTok{swelling)}\OperatorTok{+}\DecValTok{1}\NormalTok{, }\DataTypeTok{cex =} \FloatTok{1.7}\NormalTok{)}
\KeywordTok{nodelabels}\NormalTok{(}\DataTypeTok{pie =}\NormalTok{ m1}\OperatorTok{$}\NormalTok{lik.anc, }\DataTypeTok{piecol =} \KeywordTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"red"}\NormalTok{), }\DataTypeTok{cex =} \FloatTok{0.8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Now we can run a similar analysis but let's assume that rates of evolution can vary by setting model to \textbf{ARD} (All Rates Different).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m2 \textless{}{-}}\StringTok{ }\KeywordTok{ace}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ macaques}\OperatorTok{$}\NormalTok{swelling, }\DataTypeTok{phy =}\NormalTok{ macaque.tree,}
          \DataTypeTok{method =} \StringTok{"ML"}\NormalTok{, }\DataTypeTok{type =} \StringTok{"discrete"}\NormalTok{, }\DataTypeTok{model =} \StringTok{"ARD"}\NormalTok{)}

\KeywordTok{plot}\NormalTok{(macaque.tree, }\DataTypeTok{cex =} \FloatTok{0.7}\NormalTok{, }\DataTypeTok{label.offset =} \FloatTok{0.4}\NormalTok{, }\DataTypeTok{edge.width =} \DecValTok{2}\NormalTok{)}
\KeywordTok{tiplabels}\NormalTok{(}\DataTypeTok{pch =} \DecValTok{21}\NormalTok{, }\DataTypeTok{bg =} \KeywordTok{as.numeric}\NormalTok{(macaques}\OperatorTok{$}\NormalTok{swelling)}\OperatorTok{+}\DecValTok{1}\NormalTok{, }\DataTypeTok{cex =} \FloatTok{1.7}\NormalTok{)}
\KeywordTok{nodelabels}\NormalTok{(}\DataTypeTok{pie =}\NormalTok{ m2}\OperatorTok{$}\NormalTok{lik.anc, }\DataTypeTok{piecol =} \KeywordTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"red"}\NormalTok{), }\DataTypeTok{cex =} \FloatTok{0.8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-77-1} \end{center}

As you can see, the different model of evolution makes a big difference to the results. Which model you choose to use depends on which assumptions you think are justified. Is it fair to assume that the rate of evolution of conspicuous sexual swelling would be constant across the tree as in the equal rates model?

\hypertarget{stochastic-character-mapping}{%
\section{Stochastic Character Mapping}\label{stochastic-character-mapping}}

Stochastic character mapping uses an \textbf{MCMC} (Markov chain Monte-Carlo) approach to sample possible reconstructions from a posterior probability distribution.

Think of the posterior probability distribution as containing all the possible evolutionary histories of the trait in question. This includes some histories in which everything was in one state right up until a few generations from the present when everything swapped around at the same time to give us the distribution we see today. It also contains a history in which the trait switches between 0 and 1 every other generation essentially at random.

Obviously these kind of histories are biologically absurd but not mathematically impossible. They have low statistical probability. Certain other histories will have a high statistical probability and so there will be many similar histories in the distribution. The distribution can be thought of as a histogram with some parameter that defines each particular history.

\hypertarget{an-analogy}{%
\subsection{An Analogy}\label{an-analogy}}

Let's say that we were to plot the entire multiverse as such a distribution using the evil tendencies of one particular occupant (Rick Sanchez) of the multiverse as our parameter. All the different Ricks in all the different universes will vary in their evil tendencies. But overall, Rick's character is actually a nihilist meaning his mean evilness is around 0 when taken over the whole multiverse. Given all this, the posterior distribution of evil Ricks in the multiverse might look like this.

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-78-1} \end{center}

MCMC samples this distribution of histories in a chain. If a history has a higher likelihood than the previous sampling, it is accepted. If it is lower then it is rejected from the sample. In this way, MCMC quickly narrows down the possibilities and gives us a sample of quite likely histories.

\hypertarget{state-characters}{%
\subsection{2-State Characters}\label{state-characters}}

Let's see it in action. We'll need the \textbf{phytools} package \citep{phytools} to create our stochastic character map.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(phytools)}
\end{Highlighting}
\end{Shaded}

For this analysis (like other phytools functions) we'll need our data in a named vector rather than a data table. Let's call it swelling. The \textbf{names} function attaches the species name to each value in our new vector.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{swelling \textless{}{-}}\StringTok{ }\NormalTok{macaques}\OperatorTok{$}\NormalTok{swelling}
\KeywordTok{names}\NormalTok{(swelling) \textless{}{-}}\StringTok{ }\NormalTok{macaques}\OperatorTok{$}\NormalTok{species}
\NormalTok{swelling}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   Macaca_arctoides   Macaca_assamensis     Macaca_cyclopis Macaca_fascicularis 
                  0                   0                   1                   1 
     Macaca_fuscata        Macaca_maura      Macaca_mulatta   Macaca_nemestrina 
                  1                   1                   1                   1 
       Macaca_nigra      Macaca_radiata      Macaca_silenus       Macaca_sinica 
                  1                   0                   1                   0 
    Macaca_sylvanus    Macaca_thibetana     Macaca_tonkeana        Papio_anubis 
                  1                   0                   1                   1 
\end{verbatim}

Now we can sample character histories assuming an \emph{equal rates} model of evolution using the \textbf{make.simmap} function.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{scm1 \textless{}{-}}\StringTok{ }\KeywordTok{make.simmap}\NormalTok{(macaque.tree, }\DataTypeTok{x =}\NormalTok{ swelling, }\DataTypeTok{model =} \StringTok{"ER"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
make.simmap is sampling character histories conditioned on the transition matrix

Q =
            0           1
0 -0.03185011  0.03185011
1  0.03185011 -0.03185011
(estimated using likelihood);
and (mean) root node prior probabilities
pi =
  0   1 
0.5 0.5 
\end{verbatim}

\begin{verbatim}
Done.
\end{verbatim}

Q here is the matrix of transition rates which we have constrained to be equal (model = ``ER'') which explains why the numbers match. As usual with reconstructions, the best thing is to plot them. Here we can use the phytools function \textbf{plotSimmap} to plot the special object we've created. It even has a companion function to add a legend. The first line here assigns colours to the traits.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cols \textless{}{-}}\StringTok{ }\KeywordTok{setNames}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"red"}\NormalTok{), }\KeywordTok{sort}\NormalTok{(}\KeywordTok{unique}\NormalTok{(swelling)))}
\KeywordTok{plotSimmap}\NormalTok{(scm1, cols, }\DataTypeTok{pts =}\NormalTok{ F, }\DataTypeTok{lwd =} \DecValTok{3}\NormalTok{, }\DataTypeTok{fsize =} \FloatTok{.8}\NormalTok{)}
\KeywordTok{add.simmap.legend}\NormalTok{(}\DataTypeTok{colors =}\NormalTok{ cols, }\DataTypeTok{vertical =}\NormalTok{ F, }\DataTypeTok{prompt =}\NormalTok{ F, }\DataTypeTok{x =} \DecValTok{0}\NormalTok{, }\DataTypeTok{y =} \DecValTok{10}\NormalTok{, }\DataTypeTok{fsize =} \FloatTok{.8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-83-1} 

}

\caption{Simmap showing a single possible evolutionary history of sexual swelling in macaques.}\label{fig:unnamed-chunk-83}
\end{figure}

Here you can see the single history we have sampled (yours will likely differ). The history contains branches painted according to the trait colour we specified and the position of the transitions on the branch mark the exact position the changes are theorised to have taken place. This is an awful lot of certainty for an ancestral state reconstruction! You should note that the one plotted here is very odd. It says that the ancestor of the group had concealed estrus and then this trait was lost 3 times independently, leaving no trace in the extant species. Given the data and tree we provided, it is hard to see how we can have any confidence in this reconstruction. What evidence have we collected that actually supports this?

However, we need to remember that this only one of the many possible histories! Our next step should be to extract a reasonable sample of these histories!

Let's sample 500 and when R has done that, we can use \textbf{describe.simmap} to summarize the sample.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{scm2 \textless{}{-}}\StringTok{ }\KeywordTok{make.simmap}\NormalTok{(macaque.tree, swelling, }\DataTypeTok{model =} \StringTok{"ER"}\NormalTok{, }\DataTypeTok{nsim =} \DecValTok{500}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
make.simmap is sampling character histories conditioned on the transition matrix

Q =
            0           1
0 -0.03185011  0.03185011
1  0.03185011 -0.03185011
(estimated using likelihood);
and (mean) root node prior probabilities
pi =
  0   1 
0.5 0.5 
\end{verbatim}

\begin{verbatim}
Done.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{scm2.sum \textless{}{-}}\StringTok{ }\KeywordTok{describe.simmap}\NormalTok{(scm2, }\DataTypeTok{plot =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

When we call up the summary, we can see some interesting details about our sample. It seems to be saying that transitions from 1 to 0 (a loss of sexual swelling) happen more frequently than gains of sexual swelling.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{scm2.sum}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
500 trees with a mapped discrete character with states:
 0, 1 

trees have 2.872 changes between states on average

changes are of the following types:
       0,1   1,0
x->y 0.758 2.114

mean total time spent in each state is:
              0          1   total
raw  17.6835904 71.4988096 89.1824
prop  0.1982857  0.8017143  1.0000
\end{verbatim}

As usual, we're going to want a summary plot. The backbone of this plot won't look quite the same as the previous one. You don't want confusing information on your plot so here it would be better to plot a blank backbone (ie a tree with just one colour of branch that doesn't match the colour of the traits) and represent the trait transitions as we did previously with pie charts. In this case the pies represent the proportion of histories in each state (1 or 0) at each node.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cols.null \textless{}{-}}\StringTok{ }\KeywordTok{setNames}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\StringTok{"darkgrey"}\NormalTok{, }\StringTok{"darkgrey"}\NormalTok{), }\KeywordTok{sort}\NormalTok{(}\KeywordTok{unique}\NormalTok{(swelling)))}
\KeywordTok{plotSimmap}\NormalTok{(scm2[[}\DecValTok{1}\NormalTok{]], }\DataTypeTok{lwd =} \DecValTok{3}\NormalTok{, }\DataTypeTok{pts =}\NormalTok{ F, }\DataTypeTok{setEnv =}\NormalTok{ T, }\DataTypeTok{colors =}\NormalTok{ cols.null, }\DataTypeTok{offset =} \FloatTok{.6}\NormalTok{)}
\KeywordTok{nodelabels}\NormalTok{(}\DataTypeTok{pie =}\NormalTok{ scm2.sum}\OperatorTok{$}\NormalTok{ace, }\DataTypeTok{piecol =}\NormalTok{ cols, }\DataTypeTok{cex =} \FloatTok{0.6}\NormalTok{)}
\KeywordTok{add.simmap.legend}\NormalTok{(}\DataTypeTok{colors =}\NormalTok{ cols, }\DataTypeTok{vertical =}\NormalTok{ F, }\DataTypeTok{prompt =}\NormalTok{ F, }\DataTypeTok{x =} \DecValTok{0}\NormalTok{, }\DataTypeTok{y =} \DecValTok{10}\NormalTok{, }\DataTypeTok{fsize =} \FloatTok{.8}\NormalTok{)}
\KeywordTok{tiplabels}\NormalTok{(}\DataTypeTok{pch =} \DecValTok{21}\NormalTok{, }\DataTypeTok{bg =} \KeywordTok{as.numeric}\NormalTok{(macaques}\OperatorTok{$}\NormalTok{swelling)}\OperatorTok{+}\DecValTok{1}\NormalTok{, }\DataTypeTok{cex =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-86-1} 

}

\caption{Summary of 500 sampled discrete character histories showing the evolution of sexual swellings in macaques.}\label{fig:unnamed-chunk-86}
\end{figure}

This analysis gives us a very similar output to the maximum likelihood analysis in the previous section. If you're intrested, give this analysis another try with different models of evolution.

\hypertarget{state-characters-1}{%
\subsection{3-State Characters}\label{state-characters-1}}

Stochastic character mapping can also be used for traits with more than one state. For example, burrowing in carnivores can be classified as 0 (no burrowing), 1 (use a burrow dug by another animal) or 2 (dig your own burrow).

\hypertarget{data-1}{%
\subsubsection{Data}\label{data-1}}

Let's load some data from a paper which investigated aposematism in terrestrial carnivores \citep{Stankowich11}. Don't forget to assign the species names to rownames to keep everything tidy while we manipulate the data. We also have a tree covering all carnivores \citep{Nyakatura12}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{carn.tree \textless{}{-}}\StringTok{ }\KeywordTok{read.nexus}\NormalTok{(}\StringTok{"carnivores\_tree.nex"}\NormalTok{)}
\NormalTok{carn.data \textless{}{-}}\StringTok{ }\KeywordTok{read.table}\NormalTok{(}\StringTok{"carnivores\_data.txt"}\NormalTok{, }\DataTypeTok{header =}\NormalTok{ T)}
\KeywordTok{rownames}\NormalTok{(carn.data) \textless{}{-}}\StringTok{ }\NormalTok{carn.data}\OperatorTok{$}\NormalTok{Species}
\end{Highlighting}
\end{Shaded}

If you look at the new object \textbf{carn.tree} you'll notice it is a multiPhylo object. This means it actually contains a number of trees rather than just one. For more details about this class of object, see chapter 3.

For now, we just want the first one in the list (based on the best estimates used to date the tree). I'll also prune it a bit to get rid of some of the species I'm not interested in for now.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{carn.tree \textless{}{-}}\StringTok{ }\NormalTok{carn.tree[[}\DecValTok{1}\NormalTok{]]}
\NormalTok{carn.tree \textless{}{-}}\StringTok{ }\KeywordTok{extract.clade}\NormalTok{(carn.tree, }\DataTypeTok{node =} \StringTok{"\textquotesingle{}123\textquotesingle{}"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Unlike the macaque data from earlier, the carnivore data needs a little more tidying. Now that you're more comfortable using R, you should make this standard practice whenever you load data and a tree for an analysis!

We can use the function \textbf{name.check} in the package \textbf{geiger} to help us out here \citep{geiger}. This function returns two lists. The first contains all the species that appear in the phylogeny but not in the dataset. The second has the species that occur in the data but not in the tree.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{geiger}\OperatorTok{::}\KeywordTok{name.check}\NormalTok{(}\DataTypeTok{phy =}\NormalTok{ carn.tree, }\DataTypeTok{data =}\NormalTok{ carn.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
$tree_not_data
 [1] "Arctocephalus_australis"     "Arctocephalus_forsteri"     
 [3] "Arctocephalus_galapagoensis" "Arctocephalus_gazella"      
 [5] "Arctocephalus_philippii"     "Arctocephalus_pusillus"     
 [7] "Arctocephalus_townsendi"     "Arctocephalus_tropicalis"   
 [9] "Bassaricyon_alleni"          "Bassaricyon_beddardi"       
[11] "Bassaricyon_lasius"          "Bassaricyon_pauli"          
[13] "Callorhinus_ursinus"         "Conepatus_chinga"           
[15] "Conepatus_humboldtii"        "Conepatus_semistriatus"     
[17] "Cystophora_cristata"         "Dusicyon_australis"         
[19] "Erignathus_barbatus"         "Eumetopias_jubatus"         
[21] "Halichoerus_grypus"          "Histriophoca_fasciata"      
[23] "Hydrurga_leptonyx"           "Leptonychotes_weddellii"    
[25] "Lobodon_carcinophaga"        "Lontra_provocax"            
[27] "Lutra_nippon"                "Lutra_sumatrana"            
[29] "Lycalopex_fulvipes"          "Lycalopex_griseus"          
[31] "Lycalopex_gymnocercus"       "Lycalopex_sechurae"         
[33] "Lyncodon_patagonicus"        "Martes_gwatkinsii"          
[35] "Meles_anakuma"               "Meles_leucurus"             
[37] "Melogale_everetti"           "Melogale_orientalis"        
[39] "Melogale_personata"          "Mirounga_angustirostris"    
[41] "Mirounga_leonina"            "Monachus_monachus"          
[43] "Monachus_schauinslandi"      "Monachus_tropicalis"        
[45] "Mustela_felipei"             "Mustela_itatsi"             
[47] "Mustela_kathiah"             "Mustela_lutreolina"         
[49] "Mustela_nudipes"             "Mustela_strigidorsa"        
[51] "Mustela_subpalmata"          "Nasuella_olivacea"          
[53] "Neophoca_cinerea"            "Neovison_macrodon"          
[55] "Odobenus_rosmarus"           "Ommatophoca_rossii"         
[57] "Otaria_flavescens"           "Pagophilus_groenlandicus"   
[59] "Phoca_largha"                "Phoca_vitulina"             
[61] "Phocarctos_hookeri"          "Procyon_pygmaeus"           
[63] "Pusa_caspica"                "Pusa_hispida"               
[65] "Pusa_sibirica"               "Spilogale_angustifrons"     
[67] "Urocyon_littoralis"          "Vulpes_bengalensis"         
[69] "Vulpes_ferrilata"            "Zalophus_californianus"     
[71] "Zalophus_japonicus"          "Zalophus_wollebaeki"        

$data_not_tree
 [1] "Acinonyx_jubatus"             "Arctictis_binturong"         
 [3] "Arctogalidia_trivirgata"      "Atilax_paludinosus"          
 [5] "Bdeogale_crassicauda"         "Caracal_caracal"             
 [7] "Catopuma_temminckii"          "Chrotogale_owstoni"          
 [9] "Civettictis_civetta"          "Crocuta_crocuta"             
[11] "Crossarchus_obscurus"         "Cryptoprocta_ferox"          
[13] "Cynictis_penicillata"         "Cynogale_bennettii"          
[15] "Dologale_dybowskii"           "Eupleres_goudotii"           
[17] "Felis_chaus"                  "Felis_manul"                 
[19] "Felis_margarita"              "Felis_nigripes"              
[21] "Felis_silvestris"             "Fossa_fossana"               
[23] "Galerella_sanguinea"          "Galidia_elegans"             
[25] "Genetta_abyssinica"           "Genetta_angolensis"          
[27] "Genetta_genetta"              "Genetta_servalina"           
[29] "Genetta_thierryi"             "Helogale_parvula"            
[31] "Hemigalus_derbyanus"          "Herpestes_ichneumon"         
[33] "Herpestes_javanicus"          "Herpestes_urva"              
[35] "Hyaena_brunnea"               "Hyaena_hyaena"               
[37] "Ichneumia_albicauda"          "Leopardus_geoffroyi"         
[39] "Leopardus_guigna"             "Leopardus_jacobitus"         
[41] "Leopardus_pardalis"           "Leopardus_wiedii"            
[43] "Leptailurus_serval"           "Liberiictis_kuhni"           
[45] "Lynx_canadensis"              "Lynx_lynx"                   
[47] "Lynx_pardinus"                "Lynx_rufus"                  
[49] "Macrogalidia_musschenbroekii" "Mungos_gambianus"            
[51] "Mungos_mungo"                 "Mungotictis_decemlineata"    
[53] "Nandinia_binotata"            "Neofelis_nebulosa"           
[55] "Paguma_larvata"               "Panthera_leo"                
[57] "Panthera_onca"                "Panthera_pardus"             
[59] "Panthera_tigris"              "Paracynictis_selousi"        
[61] "Paradoxurus_hermaphroditus"   "Paradoxurus_zeylonensis"     
[63] "Pardofelis_marmorata"         "Poiana_richardsonii"         
[65] "Prionailurus_bengalensis"     "Prionailurus_iriomotensis"   
[67] "Prionailurus_rubiginosus"     "Prionodon_linsang"           
[69] "Prionodon_pardicolor"         "Proteles_cristata"           
[71] "Puma_concolor"                "Salanoia_concolor"           
[73] "Suricata_suricatta"           "Uncia_uncia"                 
[75] "Viverra_megaspila"            "Viverra_tangalunga"          
[77] "Viverra_zibetha"              "Viverricula_indica"          
\end{verbatim}

The easiest thing to do first is drop the tips from the tree that we're not interested in. We can pass the whole list to the \textbf{drop.tip} function in \textbf{ape} for this \citep{ape}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{carn.tree \textless{}{-}}\StringTok{ }\KeywordTok{drop.tip}\NormalTok{(carn.tree, geiger}\OperatorTok{::}\KeywordTok{name.check}\NormalTok{(carn.tree, carn.data)}\OperatorTok{$}\NormalTok{tree\_not\_data)}
\NormalTok{geiger}\OperatorTok{::}\KeywordTok{name.check}\NormalTok{(carn.tree, carn.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
$tree_not_data
character(0)

$data_not_tree
 [1] "Acinonyx_jubatus"             "Arctictis_binturong"         
 [3] "Arctogalidia_trivirgata"      "Atilax_paludinosus"          
 [5] "Bdeogale_crassicauda"         "Caracal_caracal"             
 [7] "Catopuma_temminckii"          "Chrotogale_owstoni"          
 [9] "Civettictis_civetta"          "Crocuta_crocuta"             
[11] "Crossarchus_obscurus"         "Cryptoprocta_ferox"          
[13] "Cynictis_penicillata"         "Cynogale_bennettii"          
[15] "Dologale_dybowskii"           "Eupleres_goudotii"           
[17] "Felis_chaus"                  "Felis_manul"                 
[19] "Felis_margarita"              "Felis_nigripes"              
[21] "Felis_silvestris"             "Fossa_fossana"               
[23] "Galerella_sanguinea"          "Galidia_elegans"             
[25] "Genetta_abyssinica"           "Genetta_angolensis"          
[27] "Genetta_genetta"              "Genetta_servalina"           
[29] "Genetta_thierryi"             "Helogale_parvula"            
[31] "Hemigalus_derbyanus"          "Herpestes_ichneumon"         
[33] "Herpestes_javanicus"          "Herpestes_urva"              
[35] "Hyaena_brunnea"               "Hyaena_hyaena"               
[37] "Ichneumia_albicauda"          "Leopardus_geoffroyi"         
[39] "Leopardus_guigna"             "Leopardus_jacobitus"         
[41] "Leopardus_pardalis"           "Leopardus_wiedii"            
[43] "Leptailurus_serval"           "Liberiictis_kuhni"           
[45] "Lynx_canadensis"              "Lynx_lynx"                   
[47] "Lynx_pardinus"                "Lynx_rufus"                  
[49] "Macrogalidia_musschenbroekii" "Mungos_gambianus"            
[51] "Mungos_mungo"                 "Mungotictis_decemlineata"    
[53] "Nandinia_binotata"            "Neofelis_nebulosa"           
[55] "Paguma_larvata"               "Panthera_leo"                
[57] "Panthera_onca"                "Panthera_pardus"             
[59] "Panthera_tigris"              "Paracynictis_selousi"        
[61] "Paradoxurus_hermaphroditus"   "Paradoxurus_zeylonensis"     
[63] "Pardofelis_marmorata"         "Poiana_richardsonii"         
[65] "Prionailurus_bengalensis"     "Prionailurus_iriomotensis"   
[67] "Prionailurus_rubiginosus"     "Prionodon_linsang"           
[69] "Prionodon_pardicolor"         "Proteles_cristata"           
[71] "Puma_concolor"                "Salanoia_concolor"           
[73] "Suricata_suricatta"           "Uncia_uncia"                 
[75] "Viverra_megaspila"            "Viverra_tangalunga"          
[77] "Viverra_zibetha"              "Viverricula_indica"          
\end{verbatim}

Dropping species from your dataframe is a little more complex (and in truth not always necessary). One way of doing this is to create a \textbf{for loop} that will cycle through the list above and take a subset of the dataframe each time, removing the species in the list as it goes. There are better ways to do this but it might be helpful to become familiar with for loops which are a useful programming tool!

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pruned.data \textless{}{-}}\StringTok{ }\NormalTok{carn.data}
\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\KeywordTok{length}\NormalTok{(geiger}\OperatorTok{::}\KeywordTok{name.check}\NormalTok{(carn.tree, carn.data)}\OperatorTok{$}\NormalTok{data\_not\_tree))\{}
\NormalTok{  pruned.data \textless{}{-}}\StringTok{ }\KeywordTok{subset}\NormalTok{(pruned.data, Species}\OperatorTok{!=}\NormalTok{geiger}\OperatorTok{::}\KeywordTok{name.check}\NormalTok{(carn.tree, carn.data)}\OperatorTok{$}\NormalTok{data\_not\_tree[i])}
\NormalTok{\}}
\NormalTok{geiger}\OperatorTok{::}\KeywordTok{name.check}\NormalTok{(carn.tree, pruned.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "OK"
\end{verbatim}

Once your tree and data are cleaned up we're ready to go!

\hypertarget{analysis}{%
\subsubsection{Analysis}\label{analysis}}

As before we need to create a named vector for analysis.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{burrow\textless{}{-}pruned.data}\OperatorTok{$}\NormalTok{Burrowing}
\KeywordTok{names}\NormalTok{(burrow)\textless{}{-}pruned.data}\OperatorTok{$}\NormalTok{Species}
\end{Highlighting}
\end{Shaded}

Now we can sample a single history and plot it, this time with three colours!

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{scm3\textless{}{-}}\KeywordTok{make.simmap}\NormalTok{(carn.tree, burrow, }\DataTypeTok{model=}\StringTok{"ER"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
make.simmap is sampling character histories conditioned on the transition matrix

Q =
                     Dig a Burrow No Burrowing Use existing Burrows
Dig a Burrow          -0.05640412   0.02820206           0.02820206
No Burrowing           0.02820206  -0.05640412           0.02820206
Use existing Burrows   0.02820206   0.02820206          -0.05640412
(estimated using likelihood);
and (mean) root node prior probabilities
pi =
        Dig a Burrow         No Burrowing Use existing Burrows 
           0.3333333            0.3333333            0.3333333 
\end{verbatim}

\begin{verbatim}
Done.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cols \textless{}{-}}\StringTok{ }\KeywordTok{setNames}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\StringTok{"blue"}\NormalTok{, }\StringTok{"red"}\NormalTok{, }\StringTok{"green"}\NormalTok{), }\KeywordTok{sort}\NormalTok{(}\KeywordTok{unique}\NormalTok{(burrow)))}
\KeywordTok{plotSimmap}\NormalTok{(scm3, cols, }\DataTypeTok{pts =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{lwd =} \DecValTok{2}\NormalTok{, }\DataTypeTok{fsize =} \FloatTok{0.5}\NormalTok{)}
\KeywordTok{add.simmap.legend}\NormalTok{(}\DataTypeTok{colors =}\NormalTok{ cols, }\DataTypeTok{vertical =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{prompt =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{x =} \DecValTok{2}\NormalTok{, }\DataTypeTok{y =} \DecValTok{80}\NormalTok{, }\DataTypeTok{fsize =} \FloatTok{1.4}\NormalTok{, }\DataTypeTok{shape =} \StringTok{"circle"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-95-1} \end{center}

Let's sample 200 possible histories. This may take a few moments. For reports and publications, you should sample more than this. There's no hard rule but 1000 seems to be a good minimum for a proper analysis.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{scm4 \textless{}{-}}\StringTok{ }\KeywordTok{make.simmap}\NormalTok{(carn.tree, burrow, }\DataTypeTok{model =} \StringTok{"ER"}\NormalTok{, }\DataTypeTok{nsim =} \DecValTok{200}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
make.simmap is sampling character histories conditioned on the transition matrix

Q =
                     Dig a Burrow No Burrowing Use existing Burrows
Dig a Burrow          -0.05640412   0.02820206           0.02820206
No Burrowing           0.02820206  -0.05640412           0.02820206
Use existing Burrows   0.02820206   0.02820206          -0.05640412
(estimated using likelihood);
and (mean) root node prior probabilities
pi =
        Dig a Burrow         No Burrowing Use existing Burrows 
           0.3333333            0.3333333            0.3333333 
\end{verbatim}

\begin{verbatim}
Done.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{scm4.sum\textless{}{-}}\KeywordTok{describe.simmap}\NormalTok{(scm4, }\DataTypeTok{plot =} \OtherTok{FALSE}\NormalTok{)}
\NormalTok{scm4.sum}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
200 trees with a mapped discrete character with states:
 Dig a Burrow, No Burrowing, Use existing Burrows 

trees have 52 changes between states on average

changes are of the following types:
     Dig a Burrow,No Burrowing Dig a Burrow,Use existing Burrows
x->y                      7.26                             12.24
     No Burrowing,Dig a Burrow No Burrowing,Use existing Burrows
x->y                     6.925                              5.99
     Use existing Burrows,Dig a Burrow Use existing Burrows,No Burrowing
x->y                            12.265                              7.32

mean total time spent in each state is:
     Dig a Burrow No Burrowing Use existing Burrows total
raw   366.1971509  214.5972284          350.2056207   931
prop    0.3933374    0.2305019            0.3761607     1
\end{verbatim}

Finally we can plot the summary of the analysis as before.

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-97-1} \end{center}

\hypertarget{further-info-2}{%
\section{Further info}\label{further-info-2}}

For more information about ancestral state reconstruction check out a review of the method by Joy \emph{et al}. \citep{Joy16} and chapter 3 of \emph{The comparative approach in evolutionary anthropology and biology} \citep{Nunn11}.

For more information about the phytools package \citep{phytools}, the package author Liam Revell maintains an excellent blog \href{http://blog.phytools.org/}{here} where you'll find lots of useful tips and demonstrations of the package's capabilities as well as some helpful troubleshooting.

\hypertarget{asr2}{%
\chapter{Ancestral State Reconstruction II}\label{asr2}}

Previously, we looked at reconstructing the evolutionary history of binary traits, such as the presence or absence of sexual swellings in macaques, and categorical traits such as the modes of burrowing in carnivores. In this chapter, we'll be applying the same principles to continuous data.

The logic of ancestral state reconstruction applies equally to continuous traits like body size as it does to categorical traits. Here, we'll be looking at the evolutionary history of whales, dolphins and porpoises (Cetacea).

As always, check that you have set your working directory!

\hypertarget{data-2}{%
\section{Data}\label{data-2}}

The data we have here is taken from a study of the evolution of cetacean brain and body size \citep{Montgomery13}. The reduced version here contains only body mass and the log transformed body mass for 42 species.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{whale.data \textless{}{-}}\StringTok{ }\KeywordTok{read.table}\NormalTok{(}\StringTok{"whales\_data.txt"}\NormalTok{, }\DataTypeTok{header =}\NormalTok{ T)}
\KeywordTok{rownames}\NormalTok{(whale.data) \textless{}{-}}\StringTok{ }\NormalTok{whale.data}\OperatorTok{$}\NormalTok{species}
\end{Highlighting}
\end{Shaded}

\hypertarget{tree}{%
\section{Tree}\label{tree}}

We also have a tree from the \href{https://10ktrees.nunn-lab.org/}{10ktrees} project \citep{Arnold10}. For more information about this website, see chapter 3.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{whale.tree \textless{}{-}}\StringTok{ }\KeywordTok{read.nexus}\NormalTok{(}\StringTok{"whales\_tree.nex"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We need to check the data and tree match up. Get into this habit! It will save you a lot of time and patience.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rownames}\NormalTok{(whale.data) \textless{}{-}}\StringTok{ }\NormalTok{whale.data}\OperatorTok{$}\NormalTok{species}
\NormalTok{geiger}\OperatorTok{::}\KeywordTok{name.check}\NormalTok{(whale.tree, whale.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
$tree_not_data
 [1] "Balaenoptera_acutorostrata" "Balaenoptera_bonaerensis"  
 [3] "Balaenoptera_edeni"         "Berardius_arnuxii"         
 [5] "Berardius_bairdii"          "Caperea_marginata"         
 [7] "Cephalorhynchus_eutropia"   "Cephalorhynchus_hectori"   
 [9] "Delphinus_capensis"         "Delphinus_tropicalis"      
[11] "Eubalaena_australis"        "Eubalaena_glacialis"       
[13] "Eubalaena_japonica"         "Feresa_attenuata"          
[15] "Hyperoodon_ampullatus"      "Hyperoodon_planifrons"     
[17] "Indopacetus_pacificus"      "Lagenodelphis_hosei"       
[19] "Lagenorhynchus_australis"   "Lagenorhynchus_cruciger"   
[21] "Lissodelphis_peronii"       "Mesoplodon_bidens"         
[23] "Mesoplodon_bowdoini"        "Mesoplodon_carlhubbsi"     
[25] "Mesoplodon_ginkgodens"      "Mesoplodon_grayi"          
[27] "Mesoplodon_hectori"         "Mesoplodon_layardii"       
[29] "Mesoplodon_perrini"         "Mesoplodon_peruvianus"     
[31] "Mesoplodon_stejnegeri"      "Orcaella_brevirostris"     
[33] "Orcaella_heinsohni"         "Peponocephala_electra"     
[35] "Phocoena_dioptrica"         "Phocoena_sinus"            
[37] "Platanista_minor"           "Sousa_chinensis"           
[39] "Stenella_attenuata"         "Stenella_frontalis"        
[41] "Tasmacetus_shepherdi"       "Tursiops_aduncus"          

$data_not_tree
character(0)
\end{verbatim}

Clearly some species need to be dropped from the tree!

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{whale.tree \textless{}{-}}\StringTok{ }\KeywordTok{drop.tip}\NormalTok{(whale.tree, }
\NormalTok{                       geiger}\OperatorTok{::}\KeywordTok{name.check}\NormalTok{(whale.tree, whale.data)}\OperatorTok{$}\NormalTok{tree\_not\_data)}
\NormalTok{geiger}\OperatorTok{::}\KeywordTok{name.check}\NormalTok{(whale.tree, whale.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "OK"
\end{verbatim}

\hypertarget{ancestral-state-reconstructions}{%
\section{Ancestral State Reconstructions}\label{ancestral-state-reconstructions}}

Now we're going to dive in with a reconstruction. We are using \textbf{phytools} for this analysis so we should load the package and create a named data vector \citep{phytools}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{require}\NormalTok{(phytools)}
\NormalTok{x \textless{}{-}}\StringTok{ }\NormalTok{whale.data}\OperatorTok{$}\NormalTok{log.body.mass}
\KeywordTok{names}\NormalTok{(x) \textless{}{-}}\StringTok{ }\NormalTok{whale.data}\OperatorTok{$}\NormalTok{species}
\end{Highlighting}
\end{Shaded}

The function we need is called \textbf{fastAnc} and it returns the ancestral states in a simple list.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ancstates \textless{}{-}}\StringTok{ }\KeywordTok{fastAnc}\NormalTok{(}\DataTypeTok{tree =}\NormalTok{ whale.tree,   }\CommentTok{\#Our phylogeny}
\NormalTok{                     x,                   }\CommentTok{\#Our data vector}
                     \DataTypeTok{CI =} \OtherTok{TRUE}\NormalTok{)           }\CommentTok{\#Estimate 95\% confidence intervals}
\NormalTok{ancstates}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Ancestral character estimates using fastAnc:
      43       44       45       46       47       48       49       50 
6.422936 7.205471 7.440591 7.465284 7.456463 7.511707 6.248774 6.097254 
      51       52       53       54       55       56       57       58 
6.044864 6.078069 5.983733 5.962172 5.641527 5.423179 5.255812 5.204571 
      59       60       61       62       63       64       65       66 
5.225028 5.260263 4.960018 4.901903 4.871755 4.888973 5.503471 5.567067 
      67       68       69       70       71       72       73       74 
5.710190 5.130854 4.989830 5.001555 4.960103 4.976035 5.039423 5.403331 
      75       76       77       78       79       80       81       82 
5.850745 4.870560 4.871380 4.883752 5.590679 5.292187 6.267476 5.540614 

Lower & upper 95% CIs:
      lower    upper
43 5.745860 7.100012
44 6.599516 7.811426
45 7.009526 7.871657
46 7.037792 7.892775
47 7.023487 7.889440
48 7.078101 7.945312
49 5.617637 6.879912
50 5.480639 6.713870
51 5.396996 6.692732
52 5.495449 6.660689
53 5.489021 6.478445
54 5.474786 6.449558
55 4.977189 6.305864
56 4.818460 6.027899
57 4.833079 5.678546
58 4.834286 5.574857
59 4.930739 5.519317
60 4.970172 5.550353
61 4.679687 5.240349
62 4.656292 5.147513
63 4.621817 5.121692
64 4.661301 5.116645
65 5.175817 5.831126
66 5.231290 5.902844
67 5.455762 5.964619
68 4.810518 5.451190
69 4.731256 5.248405
70 4.760819 5.242292
71 4.767162 5.153044
72 4.800446 5.151624
73 4.692067 5.386779
74 4.792073 6.014589
75 5.352644 6.348847
76 4.380205 5.360915
77 4.449659 5.293101
78 4.482168 5.285335
79 4.892863 6.288496
80 4.417990 6.166384
81 5.492347 7.042604
82 4.959783 6.121445
\end{verbatim}

To get an idea of what these results show, we should probably plot it. The \textbf{nodelabels} function maps the ancestral states listed in our \textbf{ancstates} object onto the nodes of the tree which are listed in the same order.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(whale.tree, }\DataTypeTok{cex =} \FloatTok{.8}\NormalTok{, }\DataTypeTok{label.offset =} \FloatTok{.01}\NormalTok{, }\DataTypeTok{no.margin =} \OtherTok{TRUE}\NormalTok{)}
\KeywordTok{nodelabels}\NormalTok{(}\KeywordTok{round}\NormalTok{(ancstates}\OperatorTok{$}\NormalTok{ace, }\DataTypeTok{digits =} \DecValTok{2}\NormalTok{), }\DataTypeTok{cex =} \FloatTok{.67}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-107-1} \end{center}

As is often the case, there are better ways to plot this information! The function \textbf{contMap} calls \textbf{fastAnc} and then maps the history of the trait onto the tree as a heatmap. This is a much clearer plot.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{contMap}\NormalTok{(whale.tree, x, }\DataTypeTok{fsize =} \FloatTok{.7}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-108-1} \end{center}

\hypertarget{bayestraits}{%
\section{BayesTraits}\label{bayestraits}}

Simply reconstructing the history of a trait can be very interesting. See some papers by Montgomery \emph{et al}. \citetext{\citeyear{Montgomery10}; \citeyear{Montgomery13}} for just a few great examples. However, this methodology is not limited to simply estimating the past.

Most of what we are going to do here could probably be acheived in R either with existing packages or some clever coding. However, the standard package for several analyses has been \href{http://www.evolution.rdg.ac.uk/BayesTraitsV3.0.2/BayesTraitsV3.0.2.html}{BayesTraits} for some time.

BayesTraits is a command line program, which can make it kind of intimidating. Actually (like R), it's relatively easy to use but can take some getting used to. Fortunately, \href{https://www.randigriffin.com/}{Randi Griffin} has written an excellent R package \textbf{btw} that can operate the program from within R.

It's worth noting at this point that \textbf{btw} is not written to run BayesTraits for you so that you don't have to understand the program. Randi states very clearly that the package is purely for optimising workflow. In other words, this allows you to have all your data, results and code in one place. You still need to understand how to use the program. Fortunately the \href{http://www.evolution.rdg.ac.uk/BayesTraitsV3.0.2/Files/BayesTraitsV3.0.2Manual.pdf}{manual} is very detailed.

First up, download \href{http://www.evolution.rdg.ac.uk/BayesTraitsV3.0.2/BayesTraitsV3.0.2.html}{BayesTraits} version 3 for your operating system.

\textbf{IMPORTANT!} BayesTraits output files will be written into your working directory. They will overwrite any files with the same name so don't have any files called ``data.txt'', ``tree.nex'' or ``inputfile.txt'' in this directory unless you are ok with losing them.

Next, we need to install \textbf{btw}. This isn't a CRAN archived package so we'll be installing directly from Randi Griffin's GitHub. Once installed, we can use BayesTraits from within R!

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{install.packages}\NormalTok{(}\StringTok{"devtools"}\NormalTok{)}
\KeywordTok{library}\NormalTok{(devtools)}
\KeywordTok{install\_github}\NormalTok{(}\StringTok{"rgriff23/btw"}\NormalTok{)}
\KeywordTok{library}\NormalTok{(btw)}
\end{Highlighting}
\end{Shaded}

There are some important differences in how R and BayesTraits read data that need to be summarised here.

\begin{itemize}
\tightlist
\item
  The first column of your data must contain species names.
\item
  Species names must match exactly between tree and data (but don't worry about the order).
\item
  No spaces in species names.
\item
  Discrete characters have to be of class character or factor (between 0-9) and NOT integer.
\item
  Ambiguous discrete characters can be represented as 01.
\item
  Missing data must be represented as - rather than NA.
\end{itemize}

BayesTraits consists of modules (see \href{http://www.evolution.rdg.ac.uk/BayesTraitsV3.0.2/Files/BayesTraitsV3.0.2Manual.pdf}{manual} for details) that are numbered and can be called up for different analyses.

If you can't get R and Bayestraits to play nicely together, you may want to consider using Bayestraits directly from the command prompt (Windows) or terminal (Mac). It's fairly straightforward once you've got the hang of it so be patient. Alternatively, all of this can be done with R packages like ape \citep{ape}, geiger \citep{geiger} and phytools \citep{phytools} amongst others.

\hypertarget{modelling-evolution}{%
\section{Modelling Evolution}\label{modelling-evolution}}

If we have some data about traits across a group of animals and an associated tree, we may want to ask about how that trait has evolved over time. For this we can compare the trait to models of evolutionary change.

\hypertarget{brownian-motion}{%
\subsection{Brownian Motion}\label{brownian-motion}}

Brownian motion (BM) is the most commonly used model of evolutionary change. In some ways, it can represent a kind of \emph{null model} but do not confuse this! It doesn't mean nothing is changing or that evolution is not taking place.

Brownian motion assumes three things;

\begin{itemize}
\tightlist
\item
  Evolutionary changes in a trait are randomly distributed around a mean of 0.
\item
  Evolutionary changes in a trait are independent of previous changes and changes on other branches.
\item
  Larger changes are more likely to occur on longer branches.
\end{itemize}

All this means that BM is a \emph{random walk} model in which the trait varies along the branches essentially at random.

We can use BayesTraits (via R) to model the evolution of body size in cetaceans with the assumption of Brownian motion. First we need to isolate our variables into a data table for \textbf{btw}. The way to do this is quite simple. We can simply extract the two columns we need (1 and 2) into a new object.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{BT.data \textless{}{-}}\StringTok{ }\NormalTok{whale.data[,}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{)]}
\KeywordTok{rownames}\NormalTok{(BT.data) \textless{}{-}}\StringTok{ }\OtherTok{NULL}
\KeywordTok{head}\NormalTok{(BT.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
                species log.body.mass
1       Kogia_breviceps      5.523746
2            Kogia_sima      5.226600
3      Physeter_catodon      7.573065
4  Platanista_gangetica      4.775465
5 Delphinapterus_leucas      5.803457
6     Monodon_monoceros      6.198198
\end{verbatim}

This first analysis corresponds to \textbf{Continuous: Random Walk Model A ML} in the BayesTraits \href{http://www.evolution.rdg.ac.uk/BayesTraitsV3.0.2/Files/BayesTraitsV3.0.2Manual.pdf}{manual}. We can see from the manual that the commands to run this are ``4 1 Run''. You need to be familiar with BayesTraits to interpret this so the first time you do it, you may want to do it in BayesTraits directly (via the command prompt or terminal). In essence, BayesTraits asks us questions and provides us with options for what we want it to do and \textbf{4, 1, Run} are the options to run this analysis.

Given that we know what we want to do ahead of time, we can enter the commands into a command vector in R. To run these commands through BayesTraits, R will write them into a text file so BayesTraits can interpret them when needed. Note that you don't need to enter \textbf{Run} into this vector as \textbf{btw} will take care of that for us.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{command\_vec1 \textless{}{-}}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"4"}\NormalTok{, }\StringTok{"1"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Note that if you have nodelabels in your tree, there will be an error when running BayesTraits. You can remove nodelabels without effecting the structure of your tree like this.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{whale.tree}\OperatorTok{$}\NormalTok{node.label \textless{}{-}}\StringTok{ }\OtherTok{NULL}
\end{Highlighting}
\end{Shaded}

I have a path on my desktop just for BayesTraits analyses. Remember that there must be a copy of BayesTraitsV3 stored here. That's all you need as the output will be read back into R by \textbf{btw}. You also should remember to change your working directory back if you are finished with BayesTraits. In this chunk, I've saved the existing directory at the start and reset it immediately after the analysis is completed.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wd.reset \textless{}{-}}\StringTok{ }\KeywordTok{getwd}\NormalTok{()}
\KeywordTok{setwd}\NormalTok{(}\StringTok{"\textasciitilde{}/Desktop/BayesTraits"}\NormalTok{)}
\NormalTok{m1 \textless{}{-}}\StringTok{ }\KeywordTok{bayestraits}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ BT.data, }\DataTypeTok{tree =}\NormalTok{ whale.tree, }\DataTypeTok{commands =}\NormalTok{ command\_vec1)}
\KeywordTok{setwd}\NormalTok{(wd.reset)}
\end{Highlighting}
\end{Shaded}

On we go! The object that should have appeared in your R environment contains all the outputs you need from BayesTraits. Let's have a look at the \textbf{results} component of the \textbf{Log}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m1}\OperatorTok{$}\NormalTok{Log}\OperatorTok{$}\NormalTok{results}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  Tree.No       Lh  Alpha.1 Sigma.2.1
1       1 -31.9823 6.422936  6.315406
\end{verbatim}

These results give us the Log likelihood (\textbf{Lh}), the reconstructed ancestral node (\textbf{Alpha.1}) and the phylogenetically corrected variance of the data (\textbf{Sigma.2.1}). The important thing to look at here is the log likelihood. We will use that to compare the BM model to other models.

\hypertarget{directional-evolution}{%
\subsection{Directional Evolution}\label{directional-evolution}}

So far we've looked at the random walk model of evolution. In reality, what we are usually interested in is deviations from the random walk model. We can investigate this using similar methods, but with a \textbf{directional} model.

An example of a case when we might be interested in a directional model is Cope's rule \citep{Kingsolver04, Hone05}. Cope's rule states that over time, lineages tend to have larger body sizes. So basically, on average animals tend to get bigger over evolutionary time.

Let's see if we can detect a trend in cetacean body mass. For this analysis, we need a non-ultrametric tree (a phylogram rather than a chronogram). Luckily that's what we already have. The branch lengths here describe evolutionary distance in terms of genetic change and so shorter branches indicate fewer genetic changes.

\begin{figure}[H]

{\centering \includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-116-1} 

}

\caption{Phylogenetic tree of 42 species of cetcaeans with branch lengths proportional to molecular change.}\label{fig:unnamed-chunk-116}
\end{figure}

We're using BayesTraits again so the first step is to get our data into the right format.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{BT.data \textless{}{-}}\StringTok{ }\NormalTok{whale.data[,}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{)]}
\KeywordTok{rownames}\NormalTok{(BT.data) \textless{}{-}}\StringTok{ }\OtherTok{NULL}
\end{Highlighting}
\end{Shaded}

As before, we run the random walk (BM) model first. Remember we need to set the working directory to a path where BayesTraits is stored.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{setwd}\NormalTok{(}\StringTok{"\textasciitilde{}/Desktop/BayesTraits"}\NormalTok{)}
\NormalTok{RW.commands \textless{}{-}}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"4"}\NormalTok{, }\StringTok{"1"}\NormalTok{)}
\NormalTok{RWmod \textless{}{-}}\StringTok{ }\KeywordTok{bayestraits}\NormalTok{(BT.data, whale.tree, RW.commands)}
\NormalTok{RWmod}\OperatorTok{$}\NormalTok{Log}\OperatorTok{$}\NormalTok{results}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  Tree.No       Lh  Alpha.1 Sigma.2.1
1       1 -31.9823 6.422936  6.315406
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{setwd}\NormalTok{(wd.reset)}
\end{Highlighting}
\end{Shaded}

The directional model takes a different set of commands.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{setwd}\NormalTok{(}\StringTok{"\textasciitilde{}/Desktop/BayesTraits"}\NormalTok{)}
\NormalTok{D.commands \textless{}{-}}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"5"}\NormalTok{, }\StringTok{"1"}\NormalTok{)}
\NormalTok{Dmod \textless{}{-}}\StringTok{ }\KeywordTok{bayestraits}\NormalTok{(BT.data, whale.tree, D.commands)}
\NormalTok{Dmod}\OperatorTok{$}\NormalTok{Log}\OperatorTok{$}\NormalTok{results}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  Tree.No        Lh  Alpha.1    Beta.1 Sigma.2.1
1       1 -30.22462 7.951217 -12.37922  5.808331
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{setwd}\NormalTok{(wd.reset)}
\end{Highlighting}
\end{Shaded}

Now we need to compare these models! What he have so far is two models and a log likelihood assigned to each. This means we can compare them using a \textbf{likelihood ratio test}. The general formula for an LR test is;

\[LR=2*(Lh_{ModelB} - Lh_{ModelA})\]

The result is the \textbf{likelhood ratio statistic} (LR) which is asymptotically \(\chi^2\) distributed with degrees of freedom equal to the difference in the number of parameters between the models. Model A has 1 parameter (the root value) and model B has 2 (the root and the direction of change) so the degrees of freedom are 1.

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\NormalTok{(Dmod}\OperatorTok{$}\NormalTok{Log}\OperatorTok{$}\NormalTok{results}\OperatorTok{$}\NormalTok{Lh[}\DecValTok{1}\NormalTok{] }\OperatorTok{{-}}\StringTok{ }\NormalTok{RWmod}\OperatorTok{$}\NormalTok{Log}\OperatorTok{$}\NormalTok{results}\OperatorTok{$}\NormalTok{Lh[}\DecValTok{1}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 3.515352
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1}\OperatorTok{{-}}\KeywordTok{pchisq}\NormalTok{(}\FloatTok{3.515352}\NormalTok{, }\DataTypeTok{df =} \DecValTok{1}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 0.06080274
\end{verbatim}

Note: pchisq gives the proportion of the distribution to the left of the value. To test if the model is better than the null model, we use 1 - pchisq.

The \textbf{btw} package has a function that will do all this for us. Be careful with interpretation though. Note that the p-value is different. Take this away from 1 and you have your p-value as above.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{lrtest}\NormalTok{(RWmod, Dmod)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  model1.Lh model2.Lh   LRstat      pval
1  -31.9823 -30.22462 3.515352 0.9391973
\end{verbatim}

So what have we got here? Well we have tested two models of the evolution of body size in cetacea. The first is a random walk (Brownian motion) model of evolution in which we have estimated two parameters. The second is a directional model in which we have estimated 3 parameters. Model comparison showed no significant difference between them (LR = 3.52, p = 0.06) and so we should favour the simpler, 2 parameter model. Thus we have no evidence for a directional trend in cetacean body mass evolution.

\hypertarget{changes-in-the-rate-of-evolution-of-a-trait}{%
\section{Changes in the rate of evolution of a trait}\label{changes-in-the-rate-of-evolution-of-a-trait}}

Often when investigating the evolution of a continuous trait, we might have reason to suggest that in some lineages, the rate of evolution of that trait changed.

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-122-1} \end{center}

Let's say we have a hypothesis that says the rate of change of body mass changed at the root of mysticetes (node 44). We can paint that onto the tree for demonstration using \textbf{paintSubTree} and \textbf{plotSimmap} in \textbf{phytools} \citep{phytools}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{require}\NormalTok{(phytools)}
\NormalTok{tree1 \textless{}{-}}\StringTok{ }\KeywordTok{paintSubTree}\NormalTok{(whale.tree, }\DecValTok{44}\NormalTok{, }\StringTok{"2"}\NormalTok{)}
\KeywordTok{plotSimmap}\NormalTok{(tree1, }\DataTypeTok{lwd =} \DecValTok{2}\NormalTok{, }\DataTypeTok{fsize =} \FloatTok{0.7}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-123-1} \end{center}

Now we can run the test. Here the function \textbf{brownie.lite} in \textbf{phytools} compares the single rate model to the multi-rate model we have specified!

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x \textless{}{-}}\StringTok{ }\NormalTok{whale.data}\OperatorTok{$}\NormalTok{log.body.mass}
\KeywordTok{names}\NormalTok{(x) \textless{}{-}}\StringTok{ }\NormalTok{whale.data}\OperatorTok{$}\NormalTok{species}
\NormalTok{fit \textless{}{-}}\StringTok{ }\KeywordTok{brownie.lite}\NormalTok{(tree1, x)}
\NormalTok{fit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
ML single-rate model:
    s^2 se  a   k   logL
value   6.165   1.3453  6.4229  2   -31.9823    

ML multi-rate model:
    s^2(1)  se(1)   s^2(2)  se(2)   a   k   logL    
value   7.1119  1.6786  1.2663  0.8687  6.6116  3   -30.475

P-value (based on X^2): 0.0825 

R thinks it has found the ML solution.
\end{verbatim}

Here we've found no evidence of a regime shift in mysticete cetaceans (p = 0.083).

\hypertarget{uncertainty}{%
\section{Uncertainty}\label{uncertainty}}

If you are familiar with cetaceans and their evolutionary history, you might be surprised by our findings so far in this chapter. The prevailing state of knowledge suggests that cetaceans have evolved large body sizes since the transition to the water of an approximately dog-sized ancestor at the root of our tree. Given what we know about the fossil record of cetacea, we would expect to detect an increase in body size over the tree. To solve this puzzle, we need to look at what information we provided our analysis with.

As the old saying goes, \emph{if you put garbage in, you'll get garbage out} and this seems to apply here. For example, let's look closely at our reconstructions. You can see here that both reconstructions have estimated the mass of the ancestor of cetaceans. Remember that these are log transformed data so we have to transform them back if we want to get a straightforward measurement of mass.

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{10}\OperatorTok{\^{}}\NormalTok{(RWmod}\OperatorTok{$}\NormalTok{Log}\OperatorTok{$}\NormalTok{results}\OperatorTok{$}\NormalTok{Alpha}\FloatTok{.1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 2648111
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{10}\OperatorTok{\^{}}\NormalTok{(Dmod}\OperatorTok{$}\NormalTok{Log}\OperatorTok{$}\NormalTok{results}\OperatorTok{$}\NormalTok{Alpha}\FloatTok{.1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 89375216
\end{verbatim}

So depending on our model of evolution the ancestor was either 2,648.1 kg or 89,375.2 kg. A big difference between models so which one we choose really matters.

This is even more of a problem when we look at the fossil record of cetaceans. \emph{Indohyus} (Raoellidae) is thought to be the species that most closely represents the transition to the water by cetacean ancestors \citep{Thewissen09} and its mass is estimated at around 10kg. An early species of cetacean called \emph{Pakicetus} was estimated at around 45kg. So we are orders of magnitude away from what the fossil record shows us!

This problem is well understood in phylogenetic comparative methods. In fact, all methods of ancestral state reconstruction perform very poorly when compared to what we know from the fossil record \citep{Webster02}. As you might expect, the deeper into your tree you try to estimate an ancestral state, the greater the uncertainty. This is especially clear when you look at estimating the root \citep{Gascuel14}. The solution is to incorporate fossil data in the analysis \citep{Slater12}.

\hypertarget{fossils}{%
\subsection{Fossils}\label{fossils}}

To demonstrate the importance of fossil data, let's take a closer look at the evolution of body size in cetaceans. With \textbf{fastAnc}, we found a mass of around 2,650kg for the root of the cetaceans.

The package \textbf{RRphylo} \citep{rrphylo} contains data on fossil and living cetaceans \citep{Serio19}. Using these data, we can hopefully perform a more rigorous ancestral state reconstruction \citep{Castiglione20}. Note that the values here differ betwwen datasets because the previous dataset used a log10 transformation whereas this one uses a natural log transformation!

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(RRphylo)}
\KeywordTok{data}\NormalTok{(}\StringTok{"DataCetaceans"}\NormalTok{)}
\NormalTok{DataCetaceans}\OperatorTok{$}\NormalTok{treecet {-}\textgreater{}}\StringTok{ }\NormalTok{treecet}
\NormalTok{DataCetaceans}\OperatorTok{$}\NormalTok{masscet {-}\textgreater{}}\StringTok{ }\NormalTok{masscet}
\end{Highlighting}
\end{Shaded}

The \textbf{RRphylo} function performs a variant of ancestral state reconstruction called \textbf{phylogenetic ridge regression} \citep{Castiglione20}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{RR \textless{}{-}}\StringTok{ }\KeywordTok{RRphylo}\NormalTok{(treecet, masscet)}
\end{Highlighting}
\end{Shaded}

RRphylo returns a lot of information as a list. Included in this list is the \textbf{tree} used (useful for plotting) and \textbf{aces} which contains the estimates for the traits at the nodes.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(RR}\OperatorTok{$}\NormalTok{tree, }\DataTypeTok{cex =} \FloatTok{.4}\NormalTok{, }\DataTypeTok{label.offset =} \FloatTok{.5}\NormalTok{, }\DataTypeTok{no.margin =} \OtherTok{TRUE}\NormalTok{)}
\KeywordTok{nodelabels}\NormalTok{(}\KeywordTok{round}\NormalTok{(RR}\OperatorTok{$}\NormalTok{aces, }\DataTypeTok{digits =} \DecValTok{1}\NormalTok{), }\DataTypeTok{cex =} \FloatTok{.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-128-1} \end{center}

Using this reconstruction, we can extract the mass of the root. Remember that we need \textbf{exp} to calculate the untransformed value rather than raising to the power of 10 because of the natural log transformation.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(RR}\OperatorTok{$}\NormalTok{aces[[}\DecValTok{1}\NormalTok{]])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 727063.9
\end{verbatim}

So our new estimate of the mass of the ancestor of cetaceans is 727.1kg. This is much closer to the estimated mass of early archeocete cetaceans like \emph{Ambulocetus natans} at about 430kg and \emph{Indocetus ramani} at around 630kg.

If we still aren't satisfied that we have included the best information we have available, we can actually \emph{fossilise} a node by passing a named list of ancestral states to the \textbf{RRphylo} function. Following the example of Castiglione \emph{et al}. \citeyearpar{Castiglione20}, we can set the node of the ancestor of mysticetes to a known mass. Here we are assuming that the most recent common ancestor of all mysticetes can be represented by the species \emph{Mystacodon selenensis} which weighed arond 150kg. Also we need to know that this ancestor is represented by the node labelled 128 in our tree object.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x \textless{}{-}}\StringTok{ }\KeywordTok{log}\NormalTok{(}\DecValTok{150000}\NormalTok{)}
\KeywordTok{names}\NormalTok{(x) \textless{}{-}}\StringTok{ "128"}
\end{Highlighting}
\end{Shaded}

Now we can pass this state to the argument \textbf{aces} in \textbf{RRphylo} and the analysis will hold node 128 at the value we have set. You should be able to see that in the following plot, the ancestor of mysticetes is reconstructed as 11.9 rather than 12.9 in the previous reconstruction.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{RR2 \textless{}{-}}\StringTok{ }\KeywordTok{RRphylo}\NormalTok{(treecet, masscet, }\DataTypeTok{aces =}\NormalTok{ x)}
\KeywordTok{plot}\NormalTok{(RR2}\OperatorTok{$}\NormalTok{tree, }\DataTypeTok{cex =} \FloatTok{.4}\NormalTok{, }\DataTypeTok{label.offset =} \FloatTok{.5}\NormalTok{, }\DataTypeTok{no.margin =} \OtherTok{TRUE}\NormalTok{)}
\KeywordTok{nodelabels}\NormalTok{(}\KeywordTok{round}\NormalTok{(RR2}\OperatorTok{$}\NormalTok{aces, }\DataTypeTok{digits =} \DecValTok{1}\NormalTok{), }\DataTypeTok{cex =} \FloatTok{.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-131-1} \end{center}

Hopefully you can see that the more fossil information you include in your reconstructions, the more reliable they are.

\hypertarget{revisiting-mysticete-body-mass}{%
\subsection{Revisiting Mysticete Body Mass}\label{revisiting-mysticete-body-mass}}

In using the fossil data we have added in here, Castiglione \emph{et al}. \citeyearpar{Castiglione20} demonstrated that mysticetes actually do conform to Cope's rule because they have an increasing trend in body size over time. This shows just how important adding in fossil data can be if you want the full picture.

This seems to suggest that we should also find a regime shift in mysticetes. Let's have a closer look. We begin again by painting the tree at the specific node leading to mysticetes.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{require}\NormalTok{(phytools)}
\NormalTok{tree2 \textless{}{-}}\StringTok{ }\KeywordTok{paintSubTree}\NormalTok{(treecet, }\DecValTok{128}\NormalTok{, }\StringTok{"2"}\NormalTok{)}
\KeywordTok{plotSimmap}\NormalTok{(tree2, }\DataTypeTok{lwd =} \DecValTok{2}\NormalTok{, }\DataTypeTok{fsize =} \FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-132-1} \end{center}

Next we run \textbf{brownie.lite} on our expanded dataset.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit \textless{}{-}}\StringTok{ }\KeywordTok{brownie.lite}\NormalTok{(tree2, masscet)}
\NormalTok{fit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
ML single-rate model:
    s^2 se  a   k   logL
value   0.2047  0.0265  13.2057 2   -178.7922   

ML multi-rate model:
    s^2(1)  se(1)   s^2(2)  se(2)   a   k   logL    
value   0.176   0.0245  0.4012  0.147   13.2056 3   -176.0958

P-value (based on X^2): 0.0202 

R thinks it has found the ML solution.
\end{verbatim}

There you have it! We can now say that we have evidence in favour of a regime shift in mysticete body size (p = 0.02).

\hypertarget{further-info-3}{%
\section{Further info}\label{further-info-3}}

We've only just scratched the surface of what is possible with ancestral state reconstruction. For some background reading, have a look at chapter 4 of \emph{The comparative approach in evolutionary anthropology and biology} \citep{Nunn11}.

\hypertarget{w2PGLS}{%
\chapter{Phylogenetic Regression}\label{w2PGLS}}

This chapter will show you how to perform phylogenetically correct regression analyses on continuous data in R. As usual, remember to set your working directory to wherever you have saved the necessary files.

\hypertarget{data-3}{%
\section{Data}\label{data-3}}

Let's load up some example primate data. You should see the dataframe appear in your environment. If you inspect the object, you will find a number of continuous variables in there for us to investigate.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{primate.data \textless{}{-}}\StringTok{ }\KeywordTok{read.table}\NormalTok{(}\StringTok{"primates\_data.txt"}\NormalTok{, }\DataTypeTok{header =}\NormalTok{ T)}
\KeywordTok{names}\NormalTok{(primate.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Order"           "Family"          "Binomial"        "AdultBodyMass_g"
[5] "GestationLen_d"  "HomeRange_km2"   "MaxLongevity_m"  "SocialGroupSize"
\end{verbatim}

\hypertarget{linear-regression}{%
\section{Linear Regression}\label{linear-regression}}

Simple linear regression will be familiar to you from LIFE223. The principle is to find out what the relationship is between two or more variables.

To see if body mass and gestation length are related in primate, the best way to go would seem to be a traditional linear regression. The funtion to perform an ordinary least squares linear regression is \textbf{lm()}. The first argument is our model, stating in this case that body mass predicts gestation length. Then we specify the data object to tell R where to find the data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m1 \textless{}{-}}\StringTok{ }\KeywordTok{lm}\NormalTok{(GestationLen\_d }\OperatorTok{\textasciitilde{}}\StringTok{ }\KeywordTok{log10}\NormalTok{(AdultBodyMass\_g), }\DataTypeTok{data =}\NormalTok{ primate.data)}
\end{Highlighting}
\end{Shaded}

You can use the summary function to see the output of your regression.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(m1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Call:
lm(formula = GestationLen_d ~ log10(AdultBodyMass_g), data = primate.data)

Residuals:
    Min      1Q  Median      3Q     Max 
-66.665 -15.762  -3.987  16.869  67.121 

Coefficients:
                       Estimate Std. Error t value Pr(>|t|)    
(Intercept)              31.775     13.927   2.281   0.0249 *  
log10(AdultBodyMass_g)   38.319      4.031   9.505 3.37e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 27.31 on 89 degrees of freedom
Multiple R-squared:  0.5038,    Adjusted R-squared:  0.4982 
F-statistic: 90.35 on 1 and 89 DF,  p-value: 3.374e-15
\end{verbatim}

The key parts of our output are the coefficients table and the three lines of output below which contain the R\textsuperscript{2} value. Here, it's telling us that our model is a significant fit to the data as we might expect. Also, the mid-range R\textsuperscript{2} (0.50) is what we'd expect given the spread of data in the plot.

We can also plot this line with \textbf{ggplot} with the following code. To plot the regression line, add the function geom\_smooth amd used the method ``lm'' to specify that I want a linear model plotted.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggplot2)}
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ primate.data, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =} \KeywordTok{log10}\NormalTok{(AdultBodyMass\_g), }\DataTypeTok{y =}\NormalTok{ GestationLen\_d)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_point}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom\_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{se =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-139-1} \end{center}

\hypertarget{phylogenetic-signal}{%
\section{Phylogenetic Signal}\label{phylogenetic-signal}}

As you know, the fact that comparative data points are not statistically independent is a problem for these kind of analyses. Therefore we need to run a phylogenetically corrected analysis.

Phylogenetic regression dates back a while and there have been many different ways to do it \citep{Grafen89, Nunn11}. To understand the logic behind the method, we will first consider the concept of phylogenetic signal.

\hypertarget{phylogenetic-signal-1}{%
\subsection{Phylogenetic signal}\label{phylogenetic-signal-1}}

Phylogenetic signal is defined as \emph{the tendency for closely related species to resemble each other more than distantly related species}.

For example, body mass is (usually) a trait with a strong phylogenetic signal. What this means in primates is that although there is a broad range of body sizes from a few tens of grams up to around 200kg, the distribution of body masses closely follows the pattern of relatedness. Large primates like orangutan, gorillas, chimps and humans are all closely related for example.

The degree of phylogenetic signal in a trait is often described using the scaling parameter \(\lambda\). \(\lambda\) varies between 0 and 1 and is used to multiply the internal branch lengths so that the tree describes the pattern of variation in the trait.

For example, take the case on the left, where \(\lambda\) = 1. In this case the tree is untransformed because the variation in the trait follows the structure of the tree. On the right, where \(\lambda\) = 0, all the internal branch lengths have been multiplied by 0 and therefore collapsed. This ``star phylogeny'' describes a pattern of variation in which the trait varies at random with respect to the phylogeny. The trait is not equal across the tree but rather the variation in the trait does not correlate to the pattern of relatedness.

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-140-1} \end{center}

\hypertarget{caper}{%
\subsection{caper}\label{caper}}

Let's run through some examples. There are a few packages that can run phylogenetic regressions in R but the one I usually go with is called caper (Comparative Analysis of Phylogenetics and Evolution in R) \citep{caper}. So first we'll need to load caper.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(caper)}
\end{Highlighting}
\end{Shaded}

Now we can load up our phylogeny using read.nexus from the ape package.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ape)}
\NormalTok{primate.tree \textless{}{-}}\StringTok{ }\KeywordTok{read.nexus}\NormalTok{(}\StringTok{"primate\_tree.nex"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The regression command in \textbf{caper} (along with some other functions) requires the data and tree to be combined in a \textbf{comparative data object}. This type of object is simply a tree and comparative data set concatenated and is created using the function \textbf{comparative.data}. We need to specify the tree object, data object, column name in the data where species names are stored and whether we want a variance-covariance matrix included (we do).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{primates \textless{}{-}}\StringTok{ }\KeywordTok{comparative.data}\NormalTok{(}\DataTypeTok{phy =}\NormalTok{ primate.tree,     }\CommentTok{\#Our tree}
                             \DataTypeTok{data =}\NormalTok{ primate.data,    }\CommentTok{\#Our data}
                             \DataTypeTok{names.col =}\NormalTok{ Binomial,   }\CommentTok{\#Data column with the species names}
                             \DataTypeTok{vcv =} \OtherTok{TRUE}\NormalTok{,             }\CommentTok{\#Variance{-}covariance matrix}
                             \DataTypeTok{na.omit =} \OtherTok{FALSE}\NormalTok{,        }\CommentTok{\#We don\textquotesingle{}t want to drop missing data}
                             \DataTypeTok{warn.dropped =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Warning in comparative.data(phy = primate.tree, data = primate.data, names.col =
Binomial, : Data dropped in compiling comparative data object
\end{verbatim}

This warning message isn't really a problem. If you look at the tree and data I provided, you'll see that the tree has about 200 species but the datafile contains data for only 91. Therefore we expected R to drop some species when compiling the comparative data object. In fact, we asked it warn us if it did so!

We can inspect the structure of the comparative data object using \textbf{str} if necessary. You should see that the object contains both the tree and the data. Either one of these (pruned from the larger objects we specified) can be extracted again if needed.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(primates)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
List of 7
 $ phy      :List of 5
  ..$ edge       : int [1:163, 1:2] 84 85 86 87 88 89 90 91 92 93 ...
  ..$ edge.length: num [1:163] 4.95 17.69 19.65 8.12 4.82 ...
  ..$ Nnode      : int 81
  ..$ tip.label  : chr [1:83] "Cercopithecus_ascanius" "Cercopithecus_cephus" "Cercopithecus_mitis" "Cercopithecus_neglectus" ...
  ..$ node.label : int [1:81] 84 85 86 87 88 89 90 91 92 93 ...
  ..- attr(*, "class")= chr "phylo"
  ..- attr(*, "order")= chr "cladewise"
 $ data     :'data.frame':  83 obs. of  7 variables:
  ..$ Order          : Factor w/ 1 level "Primates": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Family         : Factor w/ 15 levels "Aotidae","Atelidae",..: 4 4 4 4 4 4 4 5 5 6 ...
  ..$ AdultBodyMass_g: num [1:83] 3540 3445 5041 5325 5257 ...
  ..$ GestationLen_d : num [1:83] 148 170 138 172 170 ...
  ..$ HomeRange_km2  : num [1:83] 0.16 0.24 0.1 0.06 1.15 ...
  ..$ MaxLongevity_m : num [1:83] 340 276 325 316 276 ...
  ..$ SocialGroupSize: num [1:83] 26.3 11 16 4.5 16 28 91.2 1 1 1 ...
 $ data.name: chr "primate.data"
 $ phy.name : chr "primate.tree"
 $ dropped  :List of 2
  ..$ tips          : chr [1:143] "Allenopithecus_nigroviridis" "Cercopithecus_cephus_cephus" "Cercopithecus_cephus_ngottoensis" "Cercopithecus_diana" ...
  ..$ unmatched.rows: chr [1:8] "Cercopithecus_campbelli" "Cercopithecus_pogonias" "Chiropotes_albinasus" "Chiropotes_satanas" ...
 $ vcv      : 'VCV.array' num [1:83, 1:83] 72.3 69 64 62.4 64 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:83] "Cercopithecus_ascanius" "Cercopithecus_cephus" "Cercopithecus_mitis" "Cercopithecus_neglectus" ...
  .. ..$ : chr [1:83] "Cercopithecus_ascanius" "Cercopithecus_cephus" "Cercopithecus_mitis" "Cercopithecus_neglectus" ...
 $ vcv.dim  : num 2
 - attr(*, "class")= chr "comparative.data"
\end{verbatim}

\hypertarget{estimating-phylogenetic-signal}{%
\subsection{Estimating Phylogenetic Signal}\label{estimating-phylogenetic-signal}}

Let's estimate the phylogenetic signal of gestation length in primates. The key is to remember that we need to call our comparative data object and not the data file we loaded up at the start. We're running the trait on its own (hence the ``\textasciitilde{} 1'') and estimating lambda by maximum likelihood.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{signal \textless{}{-}}\StringTok{ }\KeywordTok{pgls}\NormalTok{(}\KeywordTok{log10}\NormalTok{(GestationLen\_d) }\OperatorTok{\textasciitilde{}}\StringTok{ }\DecValTok{1}\NormalTok{,}
               \DataTypeTok{data =}\NormalTok{ primates,}
               \DataTypeTok{lambda =} \StringTok{"ML"}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(signal)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Call:
pgls(formula = log10(GestationLen_d) ~ 1, data = primates, lambda = "ML")

Residuals:
      Min        1Q    Median        3Q       Max 
-0.035946 -0.007060 -0.001217  0.008039  0.049662 

Branch length transformations:

kappa  [Fix]  : 1.000
lambda [ ML]  : 0.957
   lower bound : 0.000, p = < 2.22e-16
   upper bound : 1.000, p = 0.050633
   95.0% CI   : (0.879, NA)
delta  [Fix]  : 1.000

Coefficients:
            Estimate Std. Error t value  Pr(>|t|)    
(Intercept) 2.175175   0.051457  42.272 < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.01462 on 82 degrees of freedom
Multiple R-squared:     0,  Adjusted R-squared:     0 
F-statistic:   NaN on 0 and 82 DF,  p-value: NA 
\end{verbatim}

This output has a lot in common with a basic regression output. That's because it is one! We used the \textbf{pgls} function which performs a regression with phylogenetic correction. Because we included no predictors, the value of \(\lambda\) we estimate here corresponds only to this one trait.

The key part for us is the \textbf{Branch length transformations} section of the output. \(\kappa\) and \(\delta\) are fixed at 1 and so we aren't concerned with those for now. \(\lambda\) is estimated at 0.957. That's a pretty strong phylogenetic signal.

We also have lower bound and upper bound tests. We can see that \(\lambda\) is significantly different from the lower bound of 0 (p \textless{} 2.2 x 10\textsuperscript{-16}).

The upper bound test shows us that \(\lambda\) is (narrowly) not significantly different from 1 (p = 0.051). This means that we can assume that gestation length has evolved by Brownian motion, in which case \(\lambda\) would equal 1 and the variation in trait would simply reflect the pattern of relatedness amongst species.

\hypertarget{phylogenetic-regression}{%
\section{Phylogenetic Regression}\label{phylogenetic-regression}}

Now let's have a go at performing a PGLS regression!

Let's say we have an idea that larger species of primate have longer gestations. Our plot seems to back this up but how strong is this relationship?

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-147-1} \end{center}

We found earlier that there does seem to be a relationship but ordinary least squares linear regression can't be relied upon in this situation. This is because of the statistical non-independence of data points due to shared evolutionary history!

A \textbf{phylogenetic generalised least squares regression} (PGLS) uses a covariance matrix to correct the analysis for this statistical non-independence. Put simply, the PGLS assumes the residuals are more similar in more closely related species rather than being randomly distributed as in linear regression.

As you've already seen, the function we need here is \textbf{pgls}. The model is constructed exactly as before but this time, we need to construct a full model. We'll be estimating \(\lambda\) by maximum likelihood again.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m2 \textless{}{-}}\StringTok{ }\KeywordTok{pgls}\NormalTok{(GestationLen\_d }\OperatorTok{\textasciitilde{}}\StringTok{ }\KeywordTok{log10}\NormalTok{(AdultBodyMass\_g), }\DataTypeTok{data =}\NormalTok{ primates, }\DataTypeTok{lambda =} \StringTok{"ML"}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(m2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Call:
pgls(formula = GestationLen_d ~ log10(AdultBodyMass_g), data = primates, 
    lambda = "ML")

Residuals:
     Min       1Q   Median       3Q      Max 
-13.0979  -2.4301  -0.8407   1.7269   6.9863 

Branch length transformations:

kappa  [Fix]  : 1.000
lambda [ ML]  : 0.805
   lower bound : 0.000, p = 2.6579e-12
   upper bound : 1.000, p = 1.042e-06
   95.0% CI   : (0.607, 0.920)
delta  [Fix]  : 1.000

Coefficients:
                       Estimate Std. Error t value  Pr(>|t|)    
(Intercept)             53.6444    20.9100  2.5655   0.01215 *  
log10(AdultBodyMass_g)  33.7532     5.8487  5.7710 1.394e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.513 on 81 degrees of freedom
Multiple R-squared: 0.2914, Adjusted R-squared: 0.2826 
F-statistic:  33.3 on 1 and 81 DF,  p-value: 1.394e-07 
\end{verbatim}

As you can see, our model is a significant fit to the data (F = 33.3, R\textsuperscript{2} = 0.29, p = 1.39 x 10\textsuperscript{-7}). More importantly, We've confirmed that body size has a positive effect on gestation length (\(\beta\) = 33.75, s.e. = 5.85, p = 1.39 x 10\textsuperscript{-7}). Time to plot!

A brief note here. The syntax to get \textbf{ggplot} to do this is a little more complex than base graphics (where we can just use abline(m2)!). Here I've plotted both the OLS (blue) and PGLS (red) lines so you can see how they differ.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(dplyr)}
\NormalTok{primates}\OperatorTok{$}\NormalTok{data }\OperatorTok{\%\textgreater{}\%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{my\_model =} \KeywordTok{predict}\NormalTok{(m2)) }\OperatorTok{\%\textgreater{}\%}
\StringTok{  }\KeywordTok{ggplot}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_point}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\KeywordTok{log10}\NormalTok{(AdultBodyMass\_g), GestationLen\_d)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_line}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\KeywordTok{log10}\NormalTok{(AdultBodyMass\_g), my\_model), }
            \DataTypeTok{colour =} \StringTok{"red"}\NormalTok{, }\DataTypeTok{lwd =} \DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_smooth}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\KeywordTok{log10}\NormalTok{(AdultBodyMass\_g), GestationLen\_d), }
              \DataTypeTok{method =} \StringTok{\textquotesingle{}lm\textquotesingle{}}\NormalTok{, }\DataTypeTok{se =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{"Log Body Mass"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"Gestation Length"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_text}\NormalTok{(}\DataTypeTok{x =} \DecValTok{2}\NormalTok{, }\DataTypeTok{y =} \DecValTok{230}\NormalTok{, }\DataTypeTok{label =} \StringTok{"PGLS"}\NormalTok{, }\DataTypeTok{colour =} \StringTok{"red"}\NormalTok{, }\DataTypeTok{size =} \DecValTok{4}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom\_text}\NormalTok{(}\DataTypeTok{x =} \DecValTok{2}\NormalTok{, }\DataTypeTok{y =} \DecValTok{218}\NormalTok{, }\DataTypeTok{label =} \StringTok{"OLS"}\NormalTok{, }\DataTypeTok{colour =} \StringTok{"blue"}\NormalTok{, }\DataTypeTok{size =} \DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-150-1} \end{center}

\hypertarget{model-checking}{%
\subsection{Model Checking}\label{model-checking}}

That's the basic model run nicely. Now, we need to run some diagnostic checks. We should start with the likelihood surface of \(\lambda\) since we estimated it by maximum likelihood.

We begin by using the \textbf{pgls.profile} function to extract the likelihoods and then simply plot them. What we are looking for is a single peak around our estimated value. If we get a flat surface or multiple peaks, there might be an issue somewhere.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lambda.profile \textless{}{-}}\StringTok{ }\KeywordTok{pgls.profile}\NormalTok{(m2, }\DataTypeTok{which =} \StringTok{"lambda"}\NormalTok{)}
\KeywordTok{plot}\NormalTok{(lambda.profile)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-151-1} \end{center}

This plot describes the log likelihood of \(\lambda\) across its possible range of values (0 - 1). We can clearly see that the likelihood is highest around a single point around 0.8. Check back against the model output earlier to see if this is what we would expect.

Next we need to identify any outliers in the model residuals. The first step here is to extract the residuals from the model, making sure to tell R that we want the phylogenetic residuals. The model output of pgls actually stores both phylogenetic and non-phylogenetic residuals. We can then standardise the residuals by dividing through by the square root of the variance.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res \textless{}{-}}\StringTok{ }\KeywordTok{residuals}\NormalTok{(m2, }\DataTypeTok{phylo =} \OtherTok{TRUE}\NormalTok{)}
\NormalTok{res \textless{}{-}}\StringTok{ }\NormalTok{res}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(}\KeywordTok{var}\NormalTok{(res))[}\DecValTok{1}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

The general rule of thumb is that any standardised residual with an absolute value greater than 3 is an outlier and needs to be removed from the analysis. Here, I'm just assigning the species names to the \textbf{res} object so we can tell which species are the outliers (if any).

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rownames}\NormalTok{(res) \textless{}{-}}\StringTok{ }\KeywordTok{rownames}\NormalTok{(m2}\OperatorTok{$}\NormalTok{residuals)}
\KeywordTok{rownames}\NormalTok{(res)[}\KeywordTok{abs}\NormalTok{(res)}\OperatorTok{\textgreater{}}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Microcebus_murinus" "Prolemur_simus"    
\end{verbatim}

Outliers! Maybe they're causing problems and maybe they aren't. We need to check that by re-running our analysis without them. A simple line of code will take our existing comparative data object and drop out the named outliers.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{primates.nooutliers \textless{}{-}}\StringTok{ }\NormalTok{primates[}\OperatorTok{{-}}\KeywordTok{which}\NormalTok{(}\KeywordTok{abs}\NormalTok{(res)}\OperatorTok{\textgreater{}}\DecValTok{3}\NormalTok{),]}
\end{Highlighting}
\end{Shaded}

Now simply re-run the model, remembering to direct R to the new data object.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m3 \textless{}{-}}\StringTok{ }\KeywordTok{pgls}\NormalTok{(GestationLen\_d }\OperatorTok{\textasciitilde{}}\StringTok{ }\KeywordTok{log10}\NormalTok{(AdultBodyMass\_g),}
           \DataTypeTok{data =}\NormalTok{ primates.nooutliers, }\DataTypeTok{lambda =} \StringTok{"ML"}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(m3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Call:
pgls(formula = GestationLen_d ~ log10(AdultBodyMass_g), data = primates.nooutliers, 
    lambda = "ML")

Residuals:
     Min       1Q   Median       3Q      Max 
-10.2217  -2.0473  -0.4166   1.3041  11.2824 

Branch length transformations:

kappa  [Fix]  : 1.000
lambda [ ML]  : 0.800
   lower bound : 0.000, p = 1.6399e-11
   upper bound : 1.000, p = 1.2064e-06
   95.0% CI   : (0.595, 0.918)
delta  [Fix]  : 1.000

Coefficients:
                       Estimate Std. Error t value  Pr(>|t|)    
(Intercept)             54.8023    21.1816  2.5873   0.01151 *  
log10(AdultBodyMass_g)  33.3672     5.9418  5.6156 2.815e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.53 on 79 degrees of freedom
Multiple R-squared: 0.2853, Adjusted R-squared: 0.2762 
F-statistic: 31.54 on 1 and 79 DF,  p-value: 2.815e-07 
\end{verbatim}

The results have barely changed. So it seems that although those two lemurs were outliers, they weren't effecting the analysis too much. Let's check for outliers in this new model.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res \textless{}{-}}\StringTok{ }\KeywordTok{residuals}\NormalTok{(m3, }\DataTypeTok{phylo =} \OtherTok{TRUE}\NormalTok{)}
\NormalTok{res \textless{}{-}}\StringTok{ }\NormalTok{res}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(}\KeywordTok{var}\NormalTok{(res))[}\DecValTok{1}\NormalTok{]}
\KeywordTok{rownames}\NormalTok{(res) \textless{}{-}}\StringTok{ }\KeywordTok{rownames}\NormalTok{(m3}\OperatorTok{$}\NormalTok{residuals)}
\KeywordTok{rownames}\NormalTok{(res)[}\KeywordTok{abs}\NormalTok{(res)}\OperatorTok{\textgreater{}}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Microcebus_rufus"
\end{verbatim}

Another one! Don't worry. This can happen. We need to drop the new outlier again to run the same checks.

Finally, we can check the diagnostic plots of the model. I've included some lines to help arrange the plots. To view the plots for model diagnostics, we can simply plot the model object!

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{par.default \textless{}{-}}\StringTok{ }\KeywordTok{par}\NormalTok{(}\DataTypeTok{no.readonly =}\NormalTok{ T) }\CommentTok{\#Save default plotting parameters}
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{)) }\CommentTok{\#Set the plot window to show 4 different plots}
\KeywordTok{plot}\NormalTok{(m3)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-157-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(par.default) }\CommentTok{\#Reset plot window to default}
\end{Highlighting}
\end{Shaded}

The top left panel shows the distribution of our residuals. We can see a bump near +3. That will be our outlier that needs to be dropped before we proceed any further. The top right plot closely approximates a straight line so that's good. The bottom left shows no real pattern which is also good. The bottom right graph should show a correlation (and it seems to) with the points more or less equally scattered above and below the 45\textsuperscript{o} diagonal. Along that line, the observed and fitted values would be exactly equal.

\hypertarget{conclusion}{%
\section{Conclusion}\label{conclusion}}

So that's how to perform a simple PGLS analysis. This kind of analysis is great for attempting make causal connections between traits of extant species, thus inferring a connection over evolutionary history. For example, we hypothesised that the reason some primates have longer gestation periods is that they have larger body sizes and the PGLS confirmed our suspicion. More complex regressions can include multpile predictors and that's what we'll look at next.

By the way, always make sure to check your models for outliers! In this analysis the gray mouse lemur was an outlier and we had to drop it. Outliers like this can throw off your analysis. If we hadn't checked, we would have presented the analysis in a paper and then had it invalidated when someone checked up on it. Fortunately in this case, the outliers didn't really change the outcome so the gray mouse lemur is off the hook. Look how relieved he is!

\begin{center}\includegraphics[width=7.64in]{Images/mouselemur} \end{center}

\hypertarget{bibliography}{%
\chapter{Bibliography}\label{bibliography}}

  \bibliography{CRG.bib,book.bib,packages.bib}

\end{document}
